export type BlogFact = {
  label: string;
  value: string;
};

export type BlogSection = {
  heading: string;
  paragraphs: string[];
  bullets?: string[];
};

export type BlogPost = {
  slug: string;
  title: string;
  seoTitle: string;
  description: string;
  dek: string;
  category: "교육" | "문화·전시" | "체육";
  region: string;
  audience: string;
  readingMinutes: number;
  publishedAt: string;
  modifiedAt: string;
  sourceCheckedAt: string;
  programId: string;
  programName: string;
  programStatus: string;
  officialUrl: string;
  sourceName: string;
  accent: "lime" | "violet" | "blue";
  iconPath: string;
  imageAlt: string;
  imageUrl?: string;
  imageSource?: string;
  imageLicense?: string;
  imageLicenseUrl?: string;
  eventStart?: string;
  eventEnd?: string;
  eventLocation?: string;
  intro: string[];
  facts: BlogFact[];
  takeaway: string;
  sections: BlogSection[];
  tags: string[];
};

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "geumcheon-memory-archive-adult-class-guide",
    title: "금천 시흥동 기억 기록 수업, 성인 무료 문화예술 강좌 가이드",
    seoTitle: "금천 성인 무료 문화예술 강좌 일정·신청 | 동네고고",
    description: "금천구립시흥도서관과 시흥동 일대에서 진행되는 기억 기록 문화예술 수업의 기간, 시간, 대상과 신청 전 확인할 내용을 정리했습니다.",
    dek: "동네를 기록하는 연속 수업은 강의실 수업과 현장 활동의 날짜, 이동 동선, 결과물 활용 범위를 함께 확인하면 참여 계획을 세우기 좋습니다.",
    category: "교육",
    region: "서울 금천구",
    audience: "지역의 기억과 기록 활동에 관심 있는 성인",
    readingMinutes: 4,
    publishedAt: "2026-08-29T06:39:00+09:00",
    modifiedAt: "2026-08-29T06:39:00+09:00",
    sourceCheckedAt: "2026-08-29",
    programId: "program:cultural_events:583a520e92841a94",
    programName: "[금천구립시흥도서관] 2026년 문화예술지원사업 [세 개의 길, 하나의 금천: 사라질 기억을 담다] 1기",
    programStatus: "진행중",
    officialUrl: "https://culture.seoul.go.kr/culture/culture/cultureEvent/view.do?cultcode=159261&menuNo=200011",
    sourceName: "서울시 문화행사 정보",
    accent: "lime",
    iconPath: "/markers/icon_art_class.png",
    imageAlt: "세 개의 길 하나의 금천 문화예술 기록 수업 공식 이미지",
    imageUrl: "https://culture.seoul.go.kr/cmmn/file/getImage.do?atchFileId=2678165b57cf448f89fb47b90ce6aeb6&thumb=Y",
    imageSource: "서울시 문화행사 정보",
    eventStart: "2026-09-02T00:00:00+09:00",
    eventEnd: "2026-10-28T23:59:59+09:00",
    eventLocation: "금천구립시흥도서관·시흥동 일대",
    intro: [
      "서울 금천구에서 동네의 기억을 문화예술 방식으로 기록하는 성인 강좌를 찾는다면 ‘세 개의 길, 하나의 금천’을 살펴볼 수 있습니다. 공개 정보상 2026년 9월 2일부터 10월 28일까지 금천구립시흥도서관과 시흥동 일대에서 진행됩니다.",
      "수업은 9월 2~16일과 10월 7~28일의 수요일 오전 10시부터 오후 1시까지로 안내되어 있습니다. 참가비는 무료이며, 회차별 장소와 현장 활동 준비물은 공식 안내에서 다시 확인하세요.",
    ],
    facts: [
      { label: "장소", value: "서울 금천구 금천구립시흥도서관·시흥동 일대" },
      { label: "기간", value: "2026년 9월 2일~10월 28일" },
      { label: "시간", value: "지정 수요일 10:00~13:00" },
      { label: "대상", value: "성인" },
      { label: "비용", value: "무료" },
      { label: "문의", value: "02-809-8242" },
    ],
    takeaway: "금천 시흥동의 기억을 직접 살피고 기록하는 성인 무료 연속 수업입니다. 회차별 장소와 야외 이동 여부를 먼저 확인하세요.",
    sections: [
      { heading: "지역 기록 수업은 질문 하나를 준비해 보세요", paragraphs: ["오래된 장소나 생활 풍경을 만났을 때 누구의 기억을 듣고 싶은지 질문을 하나 정해 두면 현장 기록의 방향이 선명해집니다.", "사진·메모·음성 중 자신에게 편한 기록 방식을 먼저 고르면 여러 회차의 자료를 꾸준히 정리하기 쉽습니다."] },
      { heading: "연속 과정 신청 전 체크리스트", paragraphs: ["세부 운영은 금천구립시흥도서관과 서울문화포털의 최신 안내가 최종 기준입니다."], bullets: ["9월·10월 전체 회차", "도서관과 시흥동 현장 활동 구분", "결석 회차 자료 제공 여부", "걷기 편한 복장과 준비물", "기록물 공개·활용 범위", "사전 신청 마감"] },
      { heading: "금천 성인 문화예술 강좌를 구체적으로 찾는 법", paragraphs: ["‘금천 성인 무료 문화예술 강좌’, ‘시흥동 지역 기록 수업’, ‘금천구립시흥도서관 9월 강좌’처럼 지역·대상·비용을 함께 검색하면 비슷한 과정과 구분하기 쉽습니다.", "과정 종료 뒤에도 이 글은 지난 프로그램 기록으로 보존합니다."] },
    ],
    tags: ["금천 성인 무료 문화예술 강좌", "시흥동 지역 기록 수업", "금천구립시흥도서관 강좌", "서울 성인 문화예술 교육"],
  },
  {
    slug: "ansan-september-online-breastfeeding-class-guide",
    title: "안산 9월 비대면 모유수유 교실, 무료 참여 확인 가이드",
    seoTitle: "안산 9월 무료 모유수유 교실 비대면 신청 | 동네고고",
    description: "안산 상록수보건소의 9월 3일 비대면 모유수유 교실을 찾는 분을 위해 무료 여부, 공식 확인 경로와 참여 전 체크리스트를 정리했습니다.",
    dek: "비대면 건강 교육은 수업 날짜뿐 아니라 대상, 접속 방법, 안내 문자 시각과 실습 준비물을 신청 전에 확인해야 당일 참여가 수월합니다.",
    category: "교육",
    region: "경기 안산시",
    audience: "모유수유를 준비하거나 도움을 받고 싶은 임산부·양육자",
    readingMinutes: 4,
    publishedAt: "2026-08-29T06:38:00+09:00",
    modifiedAt: "2026-08-29T06:38:00+09:00",
    sourceCheckedAt: "2026-08-29",
    programId: "program:eshare:2be7ceb8191bc903",
    programName: "상록수보건소 모유수유교실(9월 3일 목요일 - 비대면)",
    programStatus: "상시이용",
    officialUrl: "https://share.gg.go.kr/lecture/view?id=60980&eshare=1",
    sourceName: "공유누리",
    accent: "lime",
    iconPath: "/markers/icon_health.png",
    imageAlt: "안산 상록수보건소 9월 비대면 모유수유 교실 공식 이미지",
    imageUrl: "https://share.gg.go.kr/lecture/img/M/20260827133357395-372fe3a67cb2425b9a4964af21669be1.jpg",
    imageSource: "공유누리",
    imageLicense: "Official eShare facility image",
    intro: [
      "경기 안산에서 집에서 참여할 수 있는 모유수유 교육을 찾는다면 상록수보건소의 9월 3일 비대면 교실을 확인해 볼 수 있습니다. 공개 데이터에는 무료 프로그램으로 등록되어 있습니다.",
      "구조화된 접수 기간과 수업 시각은 제공되지 않았으므로 이 글에서는 임의로 단정하지 않습니다. 정확한 대상, 신청 마감, 접속 방법은 경기공유서비스 공식 화면에서 반드시 확인하세요.",
    ],
    facts: [
      { label: "운영기관", value: "안산 상록수보건소" },
      { label: "안내 날짜", value: "2026년 9월 3일 목요일" },
      { label: "방식", value: "비대면" },
      { label: "비용", value: "무료" },
      { label: "지역", value: "경기 안산시 상록구" },
      { label: "확인", value: "대상·수업 시각·접속 방법" },
    ],
    takeaway: "안산 상록수보건소가 안내한 무료 비대면 모유수유 교실입니다. 신청 전 정확한 시간과 온라인 참여 방법을 공식 화면에서 확인하세요.",
    sections: [
      { heading: "비대면 수업은 질문을 미리 적어 두세요", paragraphs: ["수유 자세, 통증, 수유 간격처럼 현재 가장 궁금한 내용을 두세 문장으로 적어 두면 제한된 상담 시간을 효율적으로 활용할 수 있습니다.", "실습이 포함되는지 확인하고 필요하다면 인형, 쿠션, 메모 도구를 화면 가까이에 준비하세요."] },
      { heading: "온라인 참여 전 체크리스트", paragraphs: ["수업 운영 조건은 상록수보건소와 경기공유서비스의 최신 안내가 최종 기준입니다."], bullets: ["신청 대상과 거주지 조건", "정확한 시작·종료 시각", "화상회의 앱과 접속 링크", "카메라·마이크 사용 여부", "실습 준비물", "개인 상담 가능 여부"] },
      { heading: "안산 모유수유 교육을 구체적으로 찾는 법", paragraphs: ["‘안산 9월 무료 모유수유 교실’, ‘상록수보건소 비대면 수유 교육’, ‘안산 임산부 온라인 강좌’처럼 지역·비용·참여 방식을 함께 검색하면 목적에 가까운 정보를 찾기 쉽습니다.", "날짜가 지난 뒤에도 이 글은 지역 건강교육 기록으로 보존합니다."] },
    ],
    tags: ["안산 9월 무료 모유수유 교실", "상록수보건소 비대면 교육", "안산 임산부 온라인 강좌", "경기 무료 건강교육"],
  },
  {
    slug: "chuncheon-sugna-animation-museum-exhibition-guide",
    title: "춘천 애니메이션박물관 ‘제2회 수그나’ 무료 전시 가이드",
    seoTitle: "춘천 애니메이션박물관 무료 전시 기간 | 동네고고",
    description: "춘천 애니메이션박물관에서 열리는 제2회 수그나 전시의 무료 관람 기간, 장소와 방문 전 확인할 내용을 정리했습니다.",
    dek: "짧은 기간 열리는 지역 전시는 운영 시간과 휴관일, 상설전 입장 조건, 촬영 가능 범위를 함께 확인하면 헛걸음을 줄일 수 있습니다.",
    category: "문화·전시",
    region: "강원 춘천시",
    audience: "애니메이션·지역 전시에 관심 있는 관람객",
    readingMinutes: 4,
    publishedAt: "2026-08-29T06:37:00+09:00",
    modifiedAt: "2026-08-29T06:37:00+09:00",
    sourceCheckedAt: "2026-08-29",
    programId: "program:cultureinfo_events:bc6e8945f20d8653",
    programName: "진행 제2회 수그나",
    programStatus: "진행중",
    officialUrl: "https://www.gica.or.kr/Ani/M20000/M20300/boardView?board_key=12600&page=1",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "violet",
    iconPath: "/markers/icon_exhibition.png",
    imageAlt: "춘천 애니메이션박물관 제2회 수그나 공식 전시 이미지",
    imageUrl: "https://www.culture.go.kr/upload/rdf/26/08/rdf_2026082721255267692.jpg",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    eventStart: "2026-08-25T00:00:00+09:00",
    eventEnd: "2026-09-06T23:59:59+09:00",
    eventLocation: "애니메이션박물관",
    intro: [
      "강원 춘천에서 무료 전시를 찾는다면 애니메이션박물관의 ‘제2회 수그나’를 살펴볼 수 있습니다. 공개 데이터상 전시는 2026년 8월 25일부터 9월 6일까지 진행됩니다.",
      "전시 관람료는 무료로 등록되어 있지만 박물관 전체 입장 조건과 일별 운영 시간은 별개일 수 있습니다. 방문 당일에는 강원정보문화산업진흥원 공식 안내를 우선하세요.",
    ],
    facts: [
      { label: "장소", value: "강원 춘천시 애니메이션박물관" },
      { label: "기간", value: "2026년 8월 25일~9월 6일" },
      { label: "유형", value: "전시" },
      { label: "비용", value: "무료" },
      { label: "주소", value: "강원 춘천시 서면 박사로 854" },
      { label: "문의", value: "033-245-6470" },
    ],
    takeaway: "춘천 애니메이션박물관에서 짧게 열리는 무료 전시입니다. 박물관 입장 조건과 전시 운영 시간을 방문 전에 확인하세요.",
    sections: [
      { heading: "애니메이션 전시는 움직임의 단서를 찾아보세요", paragraphs: ["한 장면을 볼 때 캐릭터의 자세, 시선, 배경의 반복 요소를 따라가면 정지된 이미지 안에서도 움직임과 이야기를 읽을 수 있습니다.", "관람 뒤 가장 기억에 남은 장면을 한 문장으로 설명해 보면 작품의 색과 구성이 더 오래 남습니다."] },
      { heading: "박물관 방문 전 체크리스트", paragraphs: ["세부 관람 조건은 애니메이션박물관 공식 공지가 최종 기준입니다."], bullets: ["전시실 위치", "일별 운영 시간", "박물관 휴관일", "전체 관람료와 무료 범위", "사진 촬영 가능 여부", "어린이 관람 동선"] },
      { heading: "춘천 무료 전시를 구체적으로 찾는 법", paragraphs: ["‘춘천 애니메이션박물관 무료 전시’, ‘춘천 9월 가족 전시’, ‘서면 박사로 전시’처럼 지역·장소·비용을 함께 검색하면 필요한 정보를 빠르게 찾을 수 있습니다.", "전시가 끝난 뒤에도 이 글은 지난 전시 기록으로 보존합니다."] },
    ],
    tags: ["춘천 애니메이션박물관 무료 전시", "춘천 9월 가족 전시", "강원 무료 전시", "춘천 애니메이션 전시"],
  },
  {
    slug: "gumi-carmen-suite-free-orchestra-guide",
    title: "구미 카르멘 모음곡 오케스트라, 무료 정기연주회 가이드",
    seoTitle: "구미 무료 오케스트라 카르멘 연주회 일정 | 동네고고",
    description: "구미시문화예술회관에서 열리는 구미 페스티발 오케스트라 카르멘 모음곡 정기연주회의 일정, 무료 여부와 관람 전 확인할 내용을 정리했습니다.",
    dek: "무료 오케스트라 공연은 공연일뿐 아니라 좌석 배부 방식, 관람 연령, 입장 시작 시각과 프로그램 순서를 미리 확인해야 합니다.",
    category: "문화·전시",
    region: "경북 구미시",
    audience: "오케스트라·오페라 음악에 관심 있는 관객",
    readingMinutes: 4,
    publishedAt: "2026-08-29T06:36:00+09:00",
    modifiedAt: "2026-08-29T06:36:00+09:00",
    sourceCheckedAt: "2026-08-29",
    programId: "program:cultureinfo_events:22d5f8b458871d56",
    programName: "제3회 구미 페스티발 오케스트라 정기연주회: Carmen suite",
    programStatus: "공연예정",
    officialUrl: "https://gucf.or.kr/Performance?menuId=MENU_0000000022&mode=detl&searchSCHED_ID=SCHED_000000001122&page=1&searchTxt=&searchDiv=",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "violet",
    iconPath: "/markers/icon_music.png",
    imageAlt: "구미 페스티발 오케스트라 카르멘 모음곡 정기연주회 공식 포스터",
    imageUrl: "https://www.culture.go.kr/upload/rdf/26/08/rdf_202608252117614969.jpg",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    eventStart: "2026-09-13T00:00:00+09:00",
    eventEnd: "2026-09-13T23:59:59+09:00",
    eventLocation: "구미시문화예술회관 대공연장",
    intro: [
      "경북 구미에서 무료 오케스트라 공연을 찾는다면 제3회 구미 페스티발 오케스트라 정기연주회를 살펴볼 수 있습니다. 공개 정보상 2026년 9월 13일 구미시문화예술회관 대공연장에서 열립니다.",
      "프로그램 제목에는 비제의 카르멘 모음곡이 안내되어 있고 전석 무료로 등록되어 있습니다. 정확한 시작 시각과 좌석 배부 방식, 관람 연령은 구미문화재단 공식 페이지에서 다시 확인하세요.",
    ],
    facts: [
      { label: "장소", value: "경북 구미시문화예술회관 대공연장" },
      { label: "공연일", value: "2026년 9월 13일" },
      { label: "프로그램", value: "카르멘 모음곡" },
      { label: "비용", value: "전석 무료" },
      { label: "주소", value: "경북 구미시 송정대로 89" },
      { label: "문의", value: "010-9937-3047" },
    ],
    takeaway: "구미문화예술회관에서 카르멘 모음곡을 만나는 무료 오케스트라 공연입니다. 입장권 배부 방식과 시작 시각을 확인하세요.",
    sections: [
      { heading: "카르멘 모음곡은 익숙한 선율의 변화를 들어보세요", paragraphs: ["빠른 리듬과 서정적인 선율이 번갈아 나타나는 지점을 따라가면 작품의 극적인 흐름을 이해하기 쉽습니다.", "목관·금관·현악이 같은 선율을 어떻게 다른 색으로 전달하는지 비교해 들어보세요."] },
      { heading: "무료 공연 관람 전 체크리스트", paragraphs: ["공연 운영은 구미문화재단의 최신 안내가 최종 기준입니다."], bullets: ["정확한 공연 시작 시각", "사전 예매·현장 배부 여부", "1인당 수령 가능 좌석", "관람 연령", "입장 마감 시각", "공연 프로그램 변경 여부"] },
      { heading: "구미 무료 클래식 공연을 찾는 검색어", paragraphs: ["‘구미 무료 오케스트라 공연’, ‘구미문화예술회관 카르멘’, ‘경북 9월 클래식 연주회’처럼 지역·비용·작품명을 함께 검색하면 필요한 공연을 구체적으로 찾기 쉽습니다.", "공연 뒤에도 이 글은 지난 프로그램 기록으로 유지합니다."] },
    ],
    tags: ["구미 무료 오케스트라 공연", "구미문화예술회관 카르멘", "경북 9월 클래식", "구미 정기연주회"],
  },
  {
    slug: "sacheon-womens-choir-free-concert-guide",
    title: "사천시 여성합창단 정기연주회, 무료 공연 관람 가이드",
    seoTitle: "사천 무료 합창 공연 일정·관람 확인 | 동네고고",
    description: "사천문화예술회관에서 열리는 제15회 사천시 여성합창단 정기연주회의 공연일, 무료 여부와 관람 전 체크리스트를 정리했습니다.",
    dek: "지역 합창 공연은 공연 날짜와 함께 시작 시각, 좌석 배부, 관람 연령, 출연진과 프로그램 순서를 확인하면 편하게 관람할 수 있습니다.",
    category: "문화·전시",
    region: "경남 사천시",
    audience: "합창·지역 문화공연에 관심 있는 관객",
    readingMinutes: 4,
    publishedAt: "2026-08-29T06:35:00+09:00",
    modifiedAt: "2026-08-29T06:35:00+09:00",
    sourceCheckedAt: "2026-08-29",
    programId: "program:cultureinfo_events:64d3ea7d9a91ad3e",
    programName: "[사천] 제15회 사천시 여성 합창단 정기 연주회",
    programStatus: "공연예정",
    officialUrl: "https://blog.naver.com/sacheoncity/224384772985",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "violet",
    iconPath: "/markers/icon_music.png",
    imageAlt: "제15회 사천시 여성합창단 정기연주회 공식 포스터",
    imageUrl: "https://www.culture.go.kr/upload/rdf/26/08/rdf_2026082721172821220.jpg",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    eventStart: "2026-09-15T00:00:00+09:00",
    eventEnd: "2026-09-15T23:59:59+09:00",
    eventLocation: "사천문화예술회관 대공연장",
    intro: [
      "경남 사천에서 무료 합창 공연을 찾는다면 제15회 사천시 여성합창단 정기연주회를 살펴볼 수 있습니다. 공개 정보상 2026년 9월 15일 사천문화예술회관 대공연장에서 열립니다.",
      "전석 무료로 등록된 공연이며, 정확한 시작 시각과 좌석 배부 방식은 사천시 공식 안내에서 확인해야 합니다. 당일에는 공연장 입장 가능 시각도 함께 확인하세요.",
    ],
    facts: [
      { label: "장소", value: "경남 사천문화예술회관 대공연장" },
      { label: "공연일", value: "2026년 9월 15일" },
      { label: "유형", value: "여성합창단 정기연주회" },
      { label: "비용", value: "전석 무료" },
      { label: "주소", value: "경남 사천시 삼천포대교로 471" },
      { label: "문의", value: "010-3569-8105" },
    ],
    takeaway: "사천문화예술회관에서 열리는 무료 여성합창 공연입니다. 시작 시각과 무료 좌석 수령 방식을 공식 안내에서 확인하세요.",
    sections: [
      { heading: "합창은 목소리가 겹치는 순간을 들어보세요", paragraphs: ["한 사람이 부르는 선율보다 여러 성부가 만나는 지점을 따라가면 합창의 깊이와 곡의 흐름을 더 잘 느낄 수 있습니다.", "가사에서 반복되는 단어와 음량이 커지는 부분을 함께 살피면 지휘가 만드는 표현도 눈에 들어옵니다."] },
      { heading: "지역 무료 공연 전 체크리스트", paragraphs: ["최종 운영 정보는 사천시와 공연장 공식 공지가 기준입니다."], bullets: ["공연 시작 시각", "좌석 사전 신청 여부", "현장 배부 시작 시각", "관람 연령", "공연장 입장 마감", "주차·대중교통 동선"] },
      { heading: "사천 무료 합창 공연을 찾는 검색어", paragraphs: ["‘사천 무료 합창 공연’, ‘사천문화예술회관 9월 연주회’, ‘경남 여성합창단 정기공연’처럼 지역·비용·공연 유형을 함께 검색하면 목적에 가까운 정보를 찾기 쉽습니다.", "공연 종료 후에도 다음 지역 공연을 비교할 수 있도록 기록을 보존합니다."] },
    ],
    tags: ["사천 무료 합창 공연", "사천문화예술회관 9월 연주회", "경남 여성합창단 공연", "사천 정기연주회"],
  },
  {
    slug: "eunpyeong-music-cities-humanities-class-guide",
    title: "은평 세계 음악도시 인문 아카데미, 4회 클래식 강좌 가이드",
    seoTitle: "은평 클래식 인문 강좌 일정·4만원 신청 | 동네고고",
    description: "은평문화예술회관에서 열리는 세계의 음악도시를 여행하다 강좌의 4회 일정, 수강료와 신청 전 확인할 내용을 정리했습니다.",
    dek: "연속 강좌는 첫날만 확인하기보다 전체 회차, 휴강일, 결석 시 자료 제공 여부와 강의실 동선을 함께 살펴보는 것이 좋습니다.",
    category: "교육",
    region: "서울 은평구",
    audience: "클래식·예술인문에 관심 있는 누구나",
    readingMinutes: 4,
    publishedAt: "2026-08-28T06:39:00+09:00",
    modifiedAt: "2026-08-28T06:39:00+09:00",
    sourceCheckedAt: "2026-08-28",
    programId: "program:cultural_events:daaffc8c9b6ecf9d",
    programName: "[은평문화재단] 예술인문 아카데미 《세계의 음악도시를 여행하다》 - 클래식으로 떠나는 음악기행",
    programStatus: "진행중",
    officialUrl: "https://culture.seoul.go.kr/culture/culture/cultureEvent/view.do?cultcode=159210&menuNo=200011",
    sourceName: "서울시 문화행사 정보",
    accent: "lime",
    iconPath: "/markers/icon_music_class.png",
    imageAlt: "은평 세계의 음악도시를 여행하다 클래식 인문 아카데미 공식 이미지",
    imageUrl: "https://culture.seoul.go.kr/cmmn/file/getImage.do?atchFileId=83f31b7c0a9945eaa5bc097cd02c5547&thumb=Y",
    imageSource: "서울시 문화행사 정보",
    eventStart: "2026-08-26T00:00:00+09:00",
    eventEnd: "2026-09-23T23:59:59+09:00",
    eventLocation: "은평문화예술회관 6강좌실",
    intro: [
      "서울 은평구에서 클래식 음악을 도시와 인문 이야기로 배우는 강좌를 찾는다면 ‘세계의 음악도시를 여행하다’를 살펴볼 수 있습니다. 공개 정보상 2026년 8월 26일부터 9월 23일까지 은평문화예술회관에서 진행됩니다.",
      "수업은 매주 수요일 오전 10시부터 낮 12시까지이며 9월 2일은 휴강으로 안내되어 있습니다. 총 4회 수강료는 4만원이고, 남은 회차 참여 가능 여부는 공식 안내에서 확인해야 합니다.",
    ],
    facts: [
      { label: "장소", value: "서울 은평구 은평문화예술회관 6강좌실" },
      { label: "기간", value: "2026년 8월 26일~9월 23일" },
      { label: "시간", value: "매주 수요일 10:00~12:00 · 9월 2일 휴강" },
      { label: "대상", value: "누구나" },
      { label: "비용", value: "총 4회 40,000원" },
      { label: "문의", value: "070-4238-4204" },
    ],
    takeaway: "은평구에서 음악과 도시 이야기를 함께 듣는 4회 예술인문 강좌입니다. 중도 신청과 결석 회차 처리 여부를 먼저 확인하세요.",
    sections: [
      { heading: "음악도시 강좌는 장소와 시대를 함께 메모해 보세요", paragraphs: ["작곡가 이름만 기록하기보다 음악이 만들어진 도시와 시대 배경을 함께 적으면 작품 간 차이를 이해하기 쉽습니다.", "강의 뒤에는 소개된 곡 한 편을 다시 듣고 기억에 남은 악기나 분위기를 짧게 남겨 보세요."] },
      { heading: "4회 과정 신청 전 체크리스트", paragraphs: ["세부 운영 조건은 은평문화재단과 서울문화포털의 최신 안내가 최종 기준입니다."], bullets: ["남은 회차 신청 가능 여부", "9월 2일 휴강 반영", "수강료 환불 기준", "강의 자료 제공 여부", "좌석과 강좌실 위치", "주차·대중교통 동선"] },
      { heading: "은평 클래식 인문 강좌를 구체적으로 찾는 법", paragraphs: ["‘은평 클래식 인문 강좌’, ‘은평문화예술회관 음악 아카데미’, ‘서울 4회 음악 강의’처럼 지역·장소·과정 수를 함께 검색하면 목적에 가까운 정보를 찾기 쉽습니다.", "일정이 끝난 뒤에도 이 글은 지난 프로그램 기록으로 보존합니다."] },
    ],
    tags: ["은평 클래식 인문 강좌", "은평문화예술회관 음악 아카데미", "서울 음악도시 강의", "은평 4회 문화 강좌"],
  },
  {
    slug: "gunsan-september-intermediate-swimming-class-guide",
    title: "군산 국민체육센터 9월 중급 수영, 평영 강습 가이드",
    seoTitle: "군산 9월 중급 수영 평영 강습 일정·신청 | 동네고고",
    description: "군산 국민체육센터 수영장의 9월 중급반 운영 기간, 저녁 강습 시간과 신청 전 확인할 내용을 정리했습니다.",
    dek: "수영 중급반은 시간표뿐 아니라 요구 영법, 대상 연령, 정원과 수강료, 휴장일을 함께 확인해야 자신의 수준에 맞게 참여할 수 있습니다.",
    category: "체육",
    region: "전북 군산시",
    audience: "배영 가능한 초등 5학년 이상·성인",
    readingMinutes: 4,
    publishedAt: "2026-08-28T06:38:00+09:00",
    modifiedAt: "2026-08-28T06:38:00+09:00",
    sourceCheckedAt: "2026-08-28",
    programId: "program:eshare:478cfb6dd3850c4b",
    programName: "['26. 9월] 18:30~19:20(중급반)-국민체육센터수영장",
    programStatus: "상시이용",
    officialUrl: "https://www.eshare.go.kr/UserPortal/Upv/UprResrcFacl/index.do?rsrc_no=HC21Q1542879",
    sourceName: "공유누리",
    accent: "blue",
    iconPath: "/markers/icon_swimming.png",
    imageAlt: "군산 국민체육센터 수영장 9월 중급반 공식 이미지",
    imageUrl: "https://www.eshare.go.kr/UserPortal/Upv/266855/fileDetail.do?file_sn=1",
    imageSource: "공유누리",
    eventStart: "2026-09-07T00:00:00+09:00",
    eventEnd: "2026-10-06T23:59:59+09:00",
    eventLocation: "군산 국민체육센터 수영장",
    intro: [
      "전북 군산에서 저녁 중급 수영 강습을 찾는다면 국민체육센터 수영장의 9월 평영반을 살펴볼 수 있습니다. 공식 공개 내용상 강습 기간은 2026년 9월 7일부터 10월 6일까지입니다.",
      "수업은 오후 6시 30분부터 7시 20분까지이며 배영이 가능한 참여자가 평영을 배우는 과정으로 안내되어 있습니다. 정확한 운영 요일과 수강료, 접수 마감은 공유누리 공식 안내에서 다시 확인하세요.",
    ],
    facts: [
      { label: "장소", value: "전북 군산시 국민체육센터 수영장" },
      { label: "기간", value: "2026년 9월 7일~10월 6일" },
      { label: "시간", value: "18:30~19:20" },
      { label: "과정", value: "중급반 · 평영 진도" },
      { label: "대상", value: "배영 가능한 초등 5학년 이상~성인" },
      { label: "정원", value: "20명" },
    ],
    takeaway: "군산 국민체육센터에서 저녁에 운영하는 평영 중급반입니다. 배영 가능 여부와 운영 요일, 수강료를 신청 전에 확인하세요.",
    sections: [
      { heading: "중급반은 속도보다 영법 기준을 확인하세요", paragraphs: ["평영 과정은 배영이 가능한 참여자를 대상으로 안내되어 있으므로 현재 호흡과 킥 수준을 스스로 점검하는 것이 좋습니다.", "수업 전 강사에게 교정받고 싶은 동작을 한 가지 정해 두면 짧은 강습 시간을 더 효율적으로 사용할 수 있습니다."] },
      { heading: "신청 전에 확인할 여섯 가지", paragraphs: ["공개된 기간 외 세부 조건은 국민체육센터와 공유누리의 최신 안내가 최종 기준입니다."], bullets: ["정확한 운영 요일", "배영 가능 수준", "초등학생 보호자 동반 기준", "수강료와 결제 방법", "수영복·수모 등 준비물", "휴장·보강 일정"] },
      { heading: "군산 9월 수영 강습을 구체적으로 찾는 법", paragraphs: ["‘군산 9월 중급 수영’, ‘국민체육센터 저녁 평영 강습’, ‘군산 성인 수영 18시 30분’처럼 지역·수준·시간을 함께 검색하면 비슷한 반과 구분하기 쉽습니다.", "강습이 끝난 뒤에도 다음 과정 비교에 참고하도록 기록을 유지합니다."] },
    ],
    tags: ["군산 9월 중급 수영", "국민체육센터 저녁 평영", "군산 성인 수영 강습", "군산 수영장 18시 30분"],
  },
  {
    slug: "bucheon-kind-noise-distant-silence-exhibition-guide",
    title: "부천 무료 기획전 ‘다정한 소음 아득한 정적’ 관람 가이드",
    seoTitle: "부천 무료 전시 다정한 소음 아득한 정적 일정 | 동네고고",
    description: "복사골문화센터에서 열리는 부천문화재단 기획전시 다정한 소음 아득한 정적의 무료 관람 기간과 방문 전 확인할 내용을 정리했습니다.",
    dek: "한 달간 이어지는 전시는 전시 기간뿐 아니라 휴관일, 관람 가능 시간, 공간 위치와 연계 프로그램을 함께 확인해야 헛걸음을 줄일 수 있습니다.",
    category: "문화·전시",
    region: "경기 부천시",
    audience: "현대미술·무료 전시 관람객",
    readingMinutes: 4,
    publishedAt: "2026-08-28T06:37:00+09:00",
    modifiedAt: "2026-08-28T06:37:00+09:00",
    sourceCheckedAt: "2026-08-28",
    programId: "program:cultureinfo_events:d17537a7d1453700",
    programName: "2026 부천문화재단 기획전시 《다정한 소음 아득한 정적》",
    programStatus: "공연예정",
    officialUrl: "https://www.bcf.or.kr/base/nrr/performance/read?performanceNo=3000308&type=&dateType=&menuLevel=3&menuNo=6&performanceManagementNo=3&searchCategory=12",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "violet",
    iconPath: "/markers/icon_exhibition.png",
    imageAlt: "부천문화재단 다정한 소음 아득한 정적 공식 전시 포스터",
    imageUrl: "https://www.culture.go.kr/upload/ucms/oneCltInfo/2026/202608/cd37edca609042d19a33e331c4222ad3.jpg",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    eventStart: "2026-09-02T00:00:00+09:00",
    eventEnd: "2026-10-02T23:59:59+09:00",
    eventLocation: "복사골문화센터",
    intro: [
      "경기 부천에서 무료 기획전시를 찾는다면 부천문화재단의 《다정한 소음 아득한 정적》을 살펴볼 수 있습니다. 공개 데이터상 전시는 2026년 9월 2일부터 10월 2일까지 복사골문화센터에서 열립니다.",
      "관람료는 무료로 안내되어 있지만 전시장 운영 시간과 휴관일은 별도 확인이 필요합니다. 방문 당일에는 부천문화재단 공식 페이지의 최신 공지를 우선하세요.",
    ],
    facts: [
      { label: "장소", value: "경기 부천시 복사골문화센터" },
      { label: "기간", value: "2026년 9월 2일~10월 2일" },
      { label: "유형", value: "부천문화재단 기획전시" },
      { label: "비용", value: "무료" },
      { label: "문의", value: "032-320-6356, 6351" },
      { label: "확인", value: "운영 시간·휴관일·연계 프로그램" },
    ],
    takeaway: "부천 복사골문화센터에서 한 달간 열리는 무료 기획전입니다. 방문 전 운영 시간과 휴관일을 확인하세요.",
    sections: [
      { heading: "제목의 대비를 관람 동선에서 찾아보세요", paragraphs: ["‘소음’과 ‘정적’처럼 대비되는 단어를 작품의 재료, 색, 공간 간격과 연결해 보면 전시를 읽는 실마리가 생깁니다.", "작품 설명을 보기 전 첫인상을 한 문장으로 적고, 관람 뒤 같은 작품을 다시 보면 시선의 변화를 확인할 수 있습니다."] },
      { heading: "무료 전시 방문 전 체크리스트", paragraphs: ["공개된 기간과 무료 여부 외 세부 운영은 부천문화재단 공식 안내가 최종 기준입니다."], bullets: ["일별 관람 가능 시간", "정기·임시 휴관일", "전시장 층과 입구", "도슨트·연계 프로그램", "사진 촬영 가능 범위", "주차·대중교통 동선"] },
      { heading: "부천 무료 현대미술 전시를 찾는 검색어", paragraphs: ["‘부천 9월 무료 전시’, ‘복사골문화센터 기획전’, ‘부천문화재단 현대미술’처럼 지역·비용·장소를 함께 검색하면 전시 정보를 구체적으로 찾기 쉽습니다.", "전시 종료 뒤에도 이 글은 지난 전시 기록으로 보존합니다."] },
    ],
    tags: ["부천 9월 무료 전시", "복사골문화센터 기획전", "부천문화재단 현대미술", "경기 무료 전시"],
  },
  {
    slug: "mapo-asian-yanggeum-festival-guide",
    title: "마포 아시아 양금 축제, 무료 주말 공연 관람 가이드",
    seoTitle: "마포 무료 아시아 양금 축제 일정·공연 시간 | 동네고고",
    description: "서울생활문화센터 서교에서 열리는 2026 아시아 양금 축제의 무료 주말 공연 일정과 관람 전 확인할 내용을 정리했습니다.",
    dek: "이틀간 열리는 국악 축제는 날짜별 시작 시각과 출연진, 입장 방식, 좌석과 악기 해설 여부를 함께 확인하면 더 편하게 즐길 수 있습니다.",
    category: "문화·전시",
    region: "서울 마포구",
    audience: "양금·국악·아시아 음악에 관심 있는 누구나",
    readingMinutes: 4,
    publishedAt: "2026-08-28T06:36:00+09:00",
    modifiedAt: "2026-08-28T06:36:00+09:00",
    sourceCheckedAt: "2026-08-28",
    programId: "program:cultural_events:09fdd1f680e0dd76",
    programName: "2026 아시아 양금 축제",
    programStatus: "진행중",
    officialUrl: "https://culture.seoul.go.kr/culture/culture/cultureEvent/view.do?cultcode=159198&menuNo=200010",
    sourceName: "서울시 문화행사 정보",
    accent: "violet",
    iconPath: "/markers/icon_traditional_music.png",
    imageAlt: "2026 아시아 양금 축제 공식 공연 이미지",
    imageUrl: "https://culture.seoul.go.kr/cmmn/file/getImage.do?atchFileId=ec7c23a0297347feadc1353b45adaac4&thumb=Y",
    imageSource: "서울시 문화행사 정보",
    eventStart: "2026-08-29T00:00:00+09:00",
    eventEnd: "2026-08-30T23:59:59+09:00",
    eventLocation: "서울생활문화센터 서교",
    intro: [
      "서울 마포구에서 아시아 전통 현악기의 소리를 만나는 무료 공연을 찾는다면 2026 아시아 양금 축제를 살펴볼 수 있습니다. 공개 정보상 축제는 8월 29일과 30일 서울생활문화센터 서교에서 열립니다.",
      "토요일 공연은 오후 6시, 일요일 공연은 오후 3시로 안내되어 있습니다. 입장 방식과 좌석, 날짜별 출연진은 서울문화포털 공식 페이지에서 다시 확인하세요.",
    ],
    facts: [
      { label: "장소", value: "서울 마포구 서울생활문화센터 서교" },
      { label: "기간", value: "2026년 8월 29~30일" },
      { label: "시간", value: "토요일 18:00 · 일요일 15:00" },
      { label: "유형", value: "양금·국악·아시아 음악 축제" },
      { label: "대상", value: "누구나" },
      { label: "비용", value: "무료" },
    ],
    takeaway: "마포구에서 이틀간 열리는 무료 아시아 양금 공연입니다. 날짜별 시작 시각과 입장 방식을 공식 안내에서 확인하세요.",
    sections: [
      { heading: "양금은 지역마다 달라지는 음색을 들어보세요", paragraphs: ["비슷한 현악기라도 연주 도구와 줄의 배치, 울림통에 따라 소리가 달라집니다. 한국·중국·베트남 연주가 이어질 때 같은 음역의 질감 차이를 들어보세요.", "협업 무대에서는 전통 악기가 현대 리듬과 만나는 순간을 따라가면 공연의 구성을 이해하기 쉽습니다."] },
      { heading: "주말 공연 전에 확인할 항목", paragraphs: ["당일 운영은 현장 상황에 따라 바뀔 수 있으므로 서울문화포털의 최신 공지를 우선하세요."], bullets: ["토·일 시작 시각", "사전 신청·현장 입장", "날짜별 출연진", "좌석 배정 방식", "공연장 입장 시각", "사진·영상 촬영 기준"] },
      { heading: "마포 무료 국악 공연을 찾는 검색어", paragraphs: ["‘마포 무료 국악 공연’, ‘서울 아시아 양금 축제’, ‘서교 주말 전통음악’처럼 지역·비용·악기 이름을 함께 검색하면 필요한 일정을 빠르게 찾을 수 있습니다.", "축제가 끝난 뒤에도 지난 공연 기록으로 보존합니다."] },
    ],
    tags: ["마포 무료 국악 공연", "서울 아시아 양금 축제", "서교 주말 전통음악", "서울생활문화센터 공연"],
  },
  {
    slug: "busan-neophilharmonic-87th-concert-guide",
    title: "부산 네오필하모닉오케스트라 제87회 정기연주회 예매 가이드",
    seoTitle: "부산 네오필 제87회 정기연주회 일정·좌석 가격 | 동네고고",
    description: "부산콘서트홀에서 열리는 부산네오필하모닉오케스트라 제87회 정기연주회의 공연일, 좌석별 가격과 관람 전 확인할 내용을 정리했습니다.",
    dek: "하루 오케스트라 공연은 공연일과 함께 시작 시각, 좌석 등급, 관람 연령, 예매 취소 마감과 입장 시간을 확인해야 합니다.",
    category: "문화·전시",
    region: "부산 부산진구",
    audience: "클래식·오케스트라 공연 관객",
    readingMinutes: 4,
    publishedAt: "2026-08-28T06:35:00+09:00",
    modifiedAt: "2026-08-28T06:35:00+09:00",
    sourceCheckedAt: "2026-08-28",
    programId: "program:cultureinfo_events:8465b7fe3fde3398",
    programName: "[부산] 부산네오필하모닉오케스트라 제87회 정기연주회",
    programStatus: "공연예정",
    officialUrl: "https://classicbusan.busan.go.kr/product/ko/performance/253188",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "violet",
    iconPath: "/markers/icon_music.png",
    imageAlt: "부산네오필하모닉오케스트라 제87회 정기연주회 공식 포스터",
    imageUrl: "https://www.culture.go.kr/upload/rdf/26/08/rdf_2026082521235859591.jpg",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    imageLicense: "공공데이터포털 이용허락범위 제한 없음",
    imageLicenseUrl: "https://www.data.go.kr/data/15138930/openapi.do",
    eventStart: "2026-09-11T00:00:00+09:00",
    eventEnd: "2026-09-11T23:59:59+09:00",
    eventLocation: "부산콘서트홀",
    intro: [
      "부산에서 9월 오케스트라 공연을 찾는다면 부산네오필하모닉오케스트라 제87회 정기연주회를 살펴볼 수 있습니다. 공개 데이터상 공연은 2026년 9월 11일 부산콘서트홀에서 열립니다.",
      "좌석 가격은 R석 10만원, S석 7만원, A석 5만원, B석 3만원으로 안내되어 있습니다. 정확한 공연 시작 시각, 관람 연령과 잔여 좌석은 부산콘서트홀 공식 예매 페이지가 최종 기준입니다.",
    ],
    facts: [
      { label: "장소", value: "부산 부산진구 부산콘서트홀" },
      { label: "공연일", value: "2026년 9월 11일" },
      { label: "R석", value: "100,000원" },
      { label: "S석", value: "70,000원" },
      { label: "A·B석", value: "50,000원 · 30,000원" },
      { label: "문의", value: "070-8899-7308 / 010-3544-7308" },
    ],
    takeaway: "부산콘서트홀에서 열리는 하루 오케스트라 정기연주회입니다. 시작 시각과 관람 연령, 좌석 등급을 공식 예매 화면에서 확인하세요.",
    sections: [
      { heading: "오케스트라는 악기군 사이의 대화를 들어보세요", paragraphs: ["처음부터 모든 선율을 따라가기보다 현악기, 목관, 금관, 타악기가 번갈아 앞에 나오는 순간을 살피면 곡의 구조가 자연스럽게 들립니다.", "공연 전에 대표 곡의 첫 부분만 들어두면 현장에서 익숙한 주제를 찾는 재미가 생깁니다."] },
      { heading: "좌석 예매 전에 확인할 항목", paragraphs: ["공개 데이터에 없는 세부 운영은 부산콘서트홀의 최신 안내를 우선하세요."], bullets: ["정확한 공연 시작 시각", "관람 가능 연령", "좌석 등급별 잔여석", "예매 수수료·취소 마감", "공연장 입장 가능 시각", "주차·대중교통 동선"] },
      { heading: "부산 9월 오케스트라 공연 검색어", paragraphs: ["‘부산 9월 오케스트라 공연’, ‘부산콘서트홀 네오필 정기연주회’, ‘부산 클래식 좌석 가격’처럼 지역·장소·가격 의도를 함께 넣으면 필요한 예매 정보를 찾기 쉽습니다.", "공연이 끝난 뒤에도 이 글은 지난 공연 기록으로 보존합니다."] },
    ],
    tags: ["부산 9월 오케스트라 공연", "부산콘서트홀 네오필 정기연주회", "부산 클래식 좌석 가격", "부산진구 공연 예매"],
  },
  {
    slug: "mapo-free-parent-tiramisu-class-guide",
    title: "마포 양육자 무료 티라미수 만들기, 신청 전 확인 가이드",
    seoTitle: "마포 무료 양육자 티라미수 만들기 일정·신청 | 동네고고",
    description: "마포구 우리동네키움센터에서 열리는 양육자 티라미수 만들기의 무료 운영일, 접수 기간과 참여 전 확인할 내용을 정리했습니다.",
    dek: "한 번 열리는 요리 체험은 메뉴보다 대상, 접수 마감, 알레르기·보관 안내와 실제 활동 시간을 먼저 확인하는 편이 안전합니다.",
    category: "교육",
    region: "서울 마포구",
    audience: "양육자·성인",
    readingMinutes: 4,
    publishedAt: "2026-08-27T06:39:00+09:00",
    modifiedAt: "2026-08-27T06:39:00+09:00",
    sourceCheckedAt: "2026-08-27",
    programId: "program:reservations:dcd3fb4c263f3d2e",
    programName: "[양육자] 양육자 요리 활동(티라미수 케이크 만들기)",
    programStatus: "안내중",
    officialUrl: "https://umppa.seoul.go.kr/icare/user/chilProgrm/orgideaExprnCtzn/BD_selectOrgideaExprnCtzn.do?q_progrmCl=1000&q_placeCode=800&q_progrmSn=3315",
    sourceName: "서울시 문화행사 공공서비스예약 정보",
    accent: "lime",
    iconPath: "/markers/icon_cooking.png",
    imageAlt: "마포 양육자 티라미수 케이크 만들기 공식 프로그램 이미지",
    imageUrl: "https://umppa.seoul.go.kr/icare/webcontent/icare/upload/orgideaExprnCtznFile/2026/8/25/3c035f1a-ca66-40a4-8381-f7361459a4ae.jpg",
    imageSource: "서울시 문화행사 공공서비스예약 정보",
    eventStart: "2026-09-12T00:00:00+09:00",
    eventEnd: "2026-09-12T23:59:59+09:00",
    eventLocation: "거점 8호 우리동네키움센터 요리Yo",
    intro: [
      "서울 마포구에서 양육자가 참여할 수 있는 무료 요리 체험을 찾는다면 접수 마감부터 확인해 보세요. 티라미수 케이크 만들기는 2026년 9월 12일 거점 8호 우리동네키움센터에서 진행되는 것으로 공개되어 있습니다.",
      "접수는 9월 4일 오후 6시까지로 안내되어 있습니다. 정확한 시작 시각, 정원, 재료의 알레르기 유발 성분과 완성품 보관 방법은 신청 화면의 최신 공지가 최종 기준입니다.",
    ],
    facts: [
      { label: "장소", value: "서울 마포구 거점 8호 우리동네키움센터 요리Yo" },
      { label: "운영일", value: "2026년 9월 12일" },
      { label: "접수 마감", value: "2026년 9월 4일 18:00" },
      { label: "대상", value: "성인 양육자" },
      { label: "비용", value: "무료" },
      { label: "상태", value: "안내중" },
    ],
    takeaway: "마포구 양육자가 무료로 참여할 수 있는 단회 요리 체험입니다. 신청 전 대상·시간·재료 알레르기와 완성품 운반 방법을 확인하세요.",
    sections: [
      {
        heading: "디저트 체험은 완성품보다 과정을 나눠 보세요",
        paragraphs: [
          "티라미수는 재료를 섞고 층을 쌓는 순서가 결과에 영향을 주기 때문에 강사의 시범을 단계별로 보는 것이 좋습니다. 처음 참여한다면 각 단계에서 질감이 어떻게 달라지는지 관찰해 보세요.",
          "가정에서 다시 만들 계획이라면 재료의 정확한 양을 외우기보다 대체 가능한 재료와 냉장 보관 시간을 메모해 두면 활용하기 쉽습니다.",
        ],
      },
      {
        heading: "신청 전에 확인할 여섯 가지",
        paragraphs: ["공개된 날짜와 무료 여부 외 세부 운영 조건은 우리동네키움센터 공식 안내를 우선해야 합니다."],
        bullets: ["정확한 시작·종료 시각", "모집 정원과 대기 신청", "유제품·달걀 등 알레르기 성분", "개인 준비물과 앞치마 제공 여부", "완성품 용기와 냉장 보관", "취소·불참 연락 방법"],
      },
      {
        heading: "마포 무료 성인 요리 체험을 찾는 방법",
        paragraphs: [
          "‘마포 무료 양육자 요리’, ‘마포구 티라미수 만들기’, ‘우리동네키움센터 성인 체험’처럼 지역·비용·대상을 함께 검색하면 비슷한 아동 프로그램과 구분하기 쉽습니다.",
          "접수가 끝났다면 동네고고에서 마포구 교육·취미 프로그램을 날짜순으로 비교해 보세요. 이 글은 일정 종료 뒤에도 지난 프로그램 기록으로 보존합니다.",
        ],
      },
    ],
    tags: ["마포 무료 양육자 요리", "마포 티라미수 만들기", "우리동네키움센터 성인 체험", "마포구 9월 무료 강좌"],
  },
  {
    slug: "seoul-heritage-wellness-walking-festival-guide",
    title: "서울 헤리티지 웰니스 걷기 페스티벌, 무료 일정 가이드",
    seoTitle: "서울 무료 걷기 페스티벌 일정·참여 확인 | 동네고고",
    description: "서울함공원과 한강변에서 열리는 헤리티지 웰니스 걷기 페스티벌의 무료 운영일, 오전·오후 시간과 참여 전 체크리스트를 정리했습니다.",
    dek: "장거리 야외 행사는 출발 시간만큼 코스 난이도, 기상, 복장과 종료 지점의 귀가 동선을 함께 확인해야 편안하게 참여할 수 있습니다.",
    category: "체육",
    region: "서울 마포구",
    audience: "전 연령 내외국인·걷기 참여자",
    readingMinutes: 4,
    publishedAt: "2026-08-27T06:38:00+09:00",
    modifiedAt: "2026-08-27T06:38:00+09:00",
    sourceCheckedAt: "2026-08-27",
    programId: "program:cultural_events:4406bda32da11a90",
    programName: "2026 서울 헤리티지 & 웰니스 걷기 페스티벌",
    programStatus: "진행중",
    officialUrl: "https://culture.seoul.go.kr/culture/culture/cultureEvent/view.do?cultcode=159190&menuNo=200010",
    sourceName: "서울시 문화행사 정보",
    accent: "blue",
    iconPath: "/markers/icon_walking.png",
    imageAlt: "2026 서울 헤리티지 웰니스 걷기 페스티벌 공식 이미지",
    imageUrl: "https://culture.seoul.go.kr/cmmn/file/getImage.do?atchFileId=da00e1aa57d74714af70f0247e963af7&thumb=Y",
    imageSource: "서울시 문화행사 정보",
    eventStart: "2026-09-19T00:00:00+09:00",
    eventEnd: "2026-09-19T23:59:59+09:00",
    eventLocation: "서울함공원 광장 및 한강변 산책로",
    intro: [
      "서울에서 무료 걷기 행사와 한강 산책을 함께 즐기고 싶다면 2026 서울 헤리티지 & 웰니스 걷기 페스티벌을 살펴볼 수 있습니다. 공개 데이터상 행사는 9월 19일 서울함공원 광장과 한강변 산책로 일대에서 열립니다.",
      "오전 시간은 9시 30분부터 오후 1시, 오후 시간은 12시 10분부터 3시로 안내되어 있습니다. 실제 집결 시각과 코스 길이, 우천 운영 여부는 공식 행사 안내에서 다시 확인하세요.",
    ],
    facts: [
      { label: "장소", value: "서울 마포구 서울함공원 광장·한강변 산책로" },
      { label: "행사일", value: "2026년 9월 19일" },
      { label: "시간", value: "오전 9:30~13:00 · 오후 12:10~15:00" },
      { label: "대상", value: "내외국인·전 연령" },
      { label: "비용", value: "무료" },
      { label: "문의", value: "02-702-7775" },
    ],
    takeaway: "서울 마포구에서 전 연령이 무료로 참여할 수 있는 하루 걷기 행사입니다. 신청 여부와 코스·집결지·기상 공지를 공식 안내에서 확인하세요.",
    sections: [
      {
        heading: "걷기 행사는 내 속도에 맞는 구간을 고르세요",
        paragraphs: [
          "행사 분위기에 맞추다 보면 평소보다 빠르게 걷기 쉽습니다. 시작 10분은 몸을 데우는 속도로 걷고, 대화가 가능한 호흡을 유지하면 끝까지 무리 없이 참여하는 데 도움이 됩니다.",
          "한강변은 그늘과 바람의 차이가 클 수 있으므로 얇은 겉옷과 물을 준비하세요. 코스 중간 이탈 가능 지점과 화장실 위치를 미리 확인하면 가족 참여도 편해집니다.",
        ],
      },
      {
        heading: "출발 전에 확인할 항목",
        paragraphs: ["행사 당일 운영은 기상과 현장 상황에 따라 바뀔 수 있으므로 최신 공지를 우선하세요."],
        bullets: ["사전 신청과 현장 접수 가능 여부", "오전·오후 집결 시각", "코스 거리와 예상 소요시간", "우천·폭염 시 변경 기준", "완주 물품과 개인 준비물", "종료 지점의 대중교통"],
      },
      {
        heading: "서울 무료 걷기 행사를 구체적으로 찾는 법",
        paragraphs: [
          "‘서울 9월 무료 걷기’, ‘마포 한강 걷기 페스티벌’, ‘서울함공원 가족 체육 행사’처럼 지역·비용·활동을 함께 검색하면 실제 참여 목적에 가까운 정보를 찾기 쉽습니다.",
          "동네고고 지도에서 서울함공원 주변의 다른 체육·문화 프로그램과 이동 시간을 함께 비교해 보세요.",
        ],
      },
    ],
    tags: ["서울 9월 무료 걷기", "마포 한강 걷기 행사", "서울함공원 페스티벌", "서울 가족 무료 체육"],
  },
  {
    slug: "busan-disabled-poetry-recital-forum-guide",
    title: "부산 장애인 시낭송포럼 ‘나의 시, 나의 무대’ 관람 가이드",
    seoTitle: "부산 장애인 시낭송포럼 일정·장소 확인 | 동네고고",
    description: "국립해양박물관에서 열리는 장애인 시낭송포럼 나의 시, 나의 무대의 날짜, 장소와 접근성·참여 전 확인할 내용을 정리했습니다.",
    dek: "시낭송 행사는 작품 정보뿐 아니라 현장 접근성, 좌석과 동행 지원, 촬영·기록 안내를 함께 확인하면 더 편안하게 참여할 수 있습니다.",
    category: "문화·전시",
    region: "부산 영도구",
    audience: "시낭송·접근성 문화행사 관심자",
    readingMinutes: 4,
    publishedAt: "2026-08-27T06:37:00+09:00",
    modifiedAt: "2026-08-27T06:37:00+09:00",
    sourceCheckedAt: "2026-08-27",
    programId: "program:cultureinfo_events:648e9200005b5052",
    programName: "[국립해양박물관] 나의 시, 나의 무대: 장애인 시낭송포럼",
    programStatus: "공연예정",
    officialUrl: "https://www.mmk.or.kr/kr/?folder=bbs&page=view&board_id=notice&idx=20419",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "violet",
    iconPath: "/markers/icon_humanities.png",
    imageAlt: "국립해양박물관 나의 시 나의 무대 장애인 시낭송포럼 공식 이미지",
    imageUrl: "https://www.culture.go.kr/upload/ucms/oneCltInfo/2026/202608/e0a49d919f2640d082cd6f146a2a39a4.png",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    eventStart: "2026-09-09T00:00:00+09:00",
    eventEnd: "2026-09-09T23:59:59+09:00",
    eventLocation: "국립해양박물관 1층 대강당",
    intro: [
      "부산 영도구에서 시와 목소리가 만나는 문화행사를 찾는다면 국립해양박물관의 ‘나의 시, 나의 무대’ 장애인 시낭송포럼을 살펴볼 수 있습니다. 공개 데이터상 행사는 2026년 9월 9일 1층 대강당에서 열립니다.",
      "현재 공개 데이터에는 확정 참가비와 세부 시작 시각이 표시되어 있지 않습니다. 참여 방식, 수어·문자통역 등 편의 지원, 휠체어 좌석과 동행인 안내는 박물관 공식 공지에서 확인하세요.",
    ],
    facts: [
      { label: "장소", value: "부산 영도구 국립해양박물관 1층 대강당" },
      { label: "행사일", value: "2026년 9월 9일" },
      { label: "유형", value: "장애인 시낭송포럼·문화행사" },
      { label: "비용", value: "공식 안내에서 확인 필요" },
      { label: "상태", value: "공연예정" },
      { label: "확인", value: "시작 시각·참여 방식·편의 지원" },
    ],
    takeaway: "부산 영도구에서 시낭송과 접근성 문화 활동을 함께 살펴볼 수 있는 하루 행사입니다. 필요한 편의 지원은 방문 전에 운영기관에 확인하세요.",
    sections: [
      {
        heading: "시낭송은 목소리의 속도와 쉼을 들어보세요",
        paragraphs: [
          "같은 시도 읽는 사람에 따라 강조되는 단어와 감정이 달라집니다. 문장의 뜻을 모두 해석하려 하기보다 목소리가 느려지는 곳과 침묵이 생기는 지점을 따라가 보세요.",
          "행사 뒤 기억에 남은 한 구절이나 장면을 기록하면 작품을 다시 찾기 쉽습니다. 촬영이나 녹음은 행사 규정과 참여자의 권리를 먼저 확인해야 합니다.",
        ],
      },
      {
        heading: "접근성과 참여 전에 확인할 내용",
        paragraphs: ["공개 데이터에 없는 지원 사항은 국립해양박물관의 최신 공지나 문의 안내가 최종 기준입니다."],
        bullets: ["정확한 시작·종료 시각", "사전 신청과 현장 참여 여부", "휠체어 좌석과 이동 동선", "수어·문자통역 등 편의 지원", "동행인 좌석과 안내 인력", "촬영·녹음 가능 범위"],
      },
      {
        heading: "부산 접근성 문화행사를 찾는 검색어",
        paragraphs: [
          "‘부산 장애인 시낭송 행사’, ‘영도구 9월 문화 포럼’, ‘국립해양박물관 접근성 행사’처럼 지역·대상·유형을 함께 검색하면 필요한 정보를 빠르게 좁힐 수 있습니다.",
          "동네고고에서는 부산의 전시·공연·교육 프로그램을 함께 비교하고 지도에서 이동 거리를 확인할 수 있습니다.",
        ],
      },
    ],
    tags: ["부산 장애인 시낭송", "영도구 9월 문화행사", "국립해양박물관 포럼", "부산 접근성 문화프로그램"],
  },
  {
    slug: "daejeon-season-wave-gugak-concert-guide",
    title: "대전 시즌 웨이브 Ⅹ 국악 공연, 1만원 예매 가이드",
    seoTitle: "대전 국악원 시즌 웨이브 Ⅹ 일정·1만원 예매 | 동네고고",
    description: "대전시립연정국악원 큰마당에서 열리는 시즌 웨이브 Ⅹ의 공연일, 전석 1만원 관람료와 예매 전 확인할 내용을 정리했습니다.",
    dek: "하루 공연은 작품명보다 정확한 시작 시각, 관람 연령, 좌석과 취소 마감을 함께 확인해야 예매 뒤 일정 착오를 줄일 수 있습니다.",
    category: "문화·전시",
    region: "대전 서구",
    audience: "국악·음악 공연 관객",
    readingMinutes: 4,
    publishedAt: "2026-08-27T06:36:00+09:00",
    modifiedAt: "2026-08-27T06:36:00+09:00",
    sourceCheckedAt: "2026-08-27",
    programId: "program:cultureinfo_events:4e0f70ae5cfc8d4f",
    programName: "[대전] 대전시립연정국악원 시즌 웨이브 Ⅹ",
    programStatus: "공연예정",
    officialUrl: "https://tickets.interpark.com/goods/26011533",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "violet",
    iconPath: "/markers/icon_traditional_music.png",
    imageAlt: "대전시립연정국악원 시즌 웨이브 Ⅹ 공식 공연 포스터",
    imageUrl: "https://www.culture.go.kr/upload/rdf/26/08/rdf_2026082521194611020.jpg",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    eventStart: "2026-09-04T00:00:00+09:00",
    eventEnd: "2026-09-04T23:59:59+09:00",
    eventLocation: "대전시립연정국악원 큰마당",
    intro: [
      "대전에서 국악과 현대적인 무대 구성을 함께 볼 공연을 찾는다면 대전시립연정국악원의 시즌 웨이브 Ⅹ를 살펴볼 수 있습니다. 공개 데이터상 공연은 2026년 9월 4일 큰마당에서 열릴 예정입니다.",
      "등록된 관람료는 전석 10,000원입니다. 실제 시작 시각, 관람 연령, 좌석과 할인 조건은 공식 예매 화면에서 결제 직전에 다시 확인하세요.",
    ],
    facts: [
      { label: "장소", value: "대전 서구 대전시립연정국악원 큰마당" },
      { label: "공연일", value: "2026년 9월 4일" },
      { label: "유형", value: "국악·음악 공연" },
      { label: "관람료", value: "전석 10,000원" },
      { label: "상태", value: "공연예정" },
      { label: "문의", value: "042-270-8500" },
    ],
    takeaway: "대전 서구에서 1만원으로 관람할 수 있는 하루 국악 공연입니다. 공연 시각과 좌석·관람 연령은 공식 예매 안내에서 최종 확인하세요.",
    sections: [
      {
        heading: "국악 공연은 음색이 겹치는 순간을 들어보세요",
        paragraphs: [
          "국악 공연을 처음 본다면 모든 장단과 악기 이름을 외울 필요는 없습니다. 낮고 긴 소리, 짧고 선명한 소리처럼 악기의 음색을 구분해 듣고 서로 만나는 지점을 찾아보세요.",
          "무대의 배치와 연주자 간 신호를 함께 살펴보면 소리가 어떻게 이어지는지 이해하기 쉽습니다. 곡 사이 해설이 있다면 다음 곡에서 확인할 한 가지 포인트만 기억해도 충분합니다.",
        ],
      },
      {
        heading: "예매 전에 확인할 다섯 가지",
        paragraphs: ["공개 데이터의 날짜와 가격 외 세부 조건은 공식 예매처 안내를 우선해야 합니다."],
        bullets: ["정확한 공연 시작·종료 시각", "관람 가능 연령", "좌석 지정과 시야", "할인 대상과 증빙", "취소·변경 마감"],
      },
      {
        heading: "대전 저렴한 국악 공연을 찾는 방법",
        paragraphs: [
          "‘대전 9월 국악 공연’, ‘대전시립연정국악원 1만원 공연’, ‘대전 서구 전통음악’처럼 지역·시기·가격을 묶으면 이름이 비슷한 공연과 구분하기 쉽습니다.",
          "공연 전후 일정은 동네고고 지도에서 주변 문화·전시 프로그램과 이동 시간을 함께 비교해 보세요.",
        ],
      },
    ],
    tags: ["대전 9월 국악 공연", "대전시립연정국악원 1만원", "시즌 웨이브 Ⅹ", "대전 서구 음악 공연"],
  },
  {
    slug: "jeonju-endless-dialogue-free-exhibition-guide",
    title: "전주 ‘평면 위의 끝없는 대화’ 무료 전시, 관람 가이드",
    seoTitle: "전주 무료 현대미술 전시 평면 위의 끝없는 대화 | 동네고고",
    description: "교동아트미술관에서 열리는 평면 위의 끝없는 대화 전시의 무료 관람 기간, 장소와 종료 전 확인할 운영 정보를 정리했습니다.",
    dek: "기간이 짧은 전시는 방문 날짜뿐 아니라 휴관일, 마지막 입장과 작품 촬영 기준을 함께 확인해야 헛걸음을 줄일 수 있습니다.",
    category: "문화·전시",
    region: "전북 전주시",
    audience: "현대미술·무료 전시 관람객",
    readingMinutes: 4,
    publishedAt: "2026-08-27T06:35:00+09:00",
    modifiedAt: "2026-08-27T06:35:00+09:00",
    sourceCheckedAt: "2026-08-27",
    programId: "program:cultureinfo_events:3b494707d0f79088",
    programName: "능동형 창작주체 현장연계 프로젝트 : 《 평면 위의 끝없는 대화 》",
    programStatus: "진행중",
    officialUrl: "https://www.jbct.or.kr/festival_detail.php?id=3532",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "violet",
    iconPath: "/markers/icon_exhibition.png",
    imageAlt: "전주 평면 위의 끝없는 대화 공식 전시 이미지",
    imageUrl: "https://www.culture.go.kr/upload/ucms/oneCltInfo/2026/202608/2c12f9c2bde94618b981a352de75c7cd.jpg",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    eventStart: "2026-08-25T00:00:00+09:00",
    eventEnd: "2026-08-30T23:59:59+09:00",
    eventLocation: "교동아트미술관",
    intro: [
      "전주에서 지금 볼 수 있는 무료 현대미술 전시를 찾는다면 교동아트미술관의 《평면 위의 끝없는 대화》를 살펴볼 수 있습니다. 공개 데이터상 전시는 2026년 8월 25일부터 30일까지 진행됩니다.",
      "전시 종료가 가까우므로 방문 전에 당일 운영시간과 마지막 입장을 확인하는 편이 좋습니다. 관람료는 무료로 등록되어 있지만 별도 행사나 해설 예약 여부는 공식 안내를 우선하세요.",
    ],
    facts: [
      { label: "장소", value: "전북 전주시 교동아트미술관" },
      { label: "전시 기간", value: "2026년 8월 25일~30일" },
      { label: "유형", value: "현대미술·현장연계 프로젝트" },
      { label: "비용", value: "무료" },
      { label: "상태", value: "진행중" },
      { label: "문의", value: "063-287-1244" },
    ],
    takeaway: "전주에서 8월 30일까지 무료로 볼 수 있는 짧은 현대미술 전시입니다. 방문일의 운영시간과 마지막 입장을 공식 안내에서 확인하세요.",
    sections: [
      {
        heading: "제목을 작품 사이의 질문으로 바꿔 보세요",
        paragraphs: [
          "‘끝없는 대화’라는 제목을 작품이 서로 어떤 질문을 주고받는지 찾는 관람 기준으로 바꿔 보세요. 비슷한 색이나 형태가 반복되는지, 한 작품의 장면이 다음 작품에서 어떻게 달라지는지 살펴볼 수 있습니다.",
          "작가 설명을 읽기 전 먼저 눈에 들어온 요소를 기록하고 설명을 읽은 뒤 생각이 달라졌는지 비교하면 전시를 오래 기억하는 데 도움이 됩니다.",
        ],
      },
      {
        heading: "짧은 전시 기간에 꼭 확인할 항목",
        paragraphs: ["전시 종료일과 실제 운영 종료 시각이 다를 수 있으므로 교동아트미술관 안내를 최종 기준으로 삼으세요."],
        bullets: ["요일별 운영시간과 휴관", "8월 30일 마지막 입장", "무료 관람 범위", "사진 촬영 가능 여부", "해설·연계 행사 일정"],
      },
      {
        heading: "전주 무료 전시를 구체적으로 찾는 법",
        paragraphs: [
          "‘전주 8월 무료 전시’, ‘교동아트미술관 현대미술’, ‘전주 한옥마을 근처 전시’처럼 지역·시기·장소를 함께 검색하면 현재 관람 가능한 전시를 찾기 쉽습니다.",
          "기간이 끝난 뒤에도 이 글은 지난 전시 기록으로 남습니다. 동네고고에서 전주 지역의 현재 전시와 문화행사를 다시 비교할 수 있습니다.",
        ],
      },
    ],
    tags: ["전주 8월 무료 전시", "교동아트미술관 현대미술", "평면 위의 끝없는 대화", "전주 한옥마을 전시"],
  },
  {
    slug: "daejeon-youth-choir-letter-concert-guide",
    title: "대전 청소년합창단 가곡 연주회, 5천원 관람 가이드",
    seoTitle: "대전 청소년합창단 노래로 보내는 편지 일정·예매 | 동네고고",
    description: "대전예술의전당에서 열리는 가곡시리즈 Ⅲ 노래로 보내는 편지의 공연일, 전석 5천원 관람료와 예매 체크리스트를 정리했습니다.",
    dek: "하루만 열리는 합창 공연은 날짜만 저장하지 말고 시작 시각, 관람 연령, 좌석과 취소 마감을 함께 확인해야 합니다.",
    category: "문화·전시",
    region: "대전 서구",
    audience: "가곡·합창 공연 관객",
    readingMinutes: 4,
    publishedAt: "2026-08-26T06:39:00+09:00",
    modifiedAt: "2026-08-26T06:39:00+09:00",
    sourceCheckedAt: "2026-08-26",
    programId: "program:cultureinfo_events:1b6770bd3340b434",
    programName: "[대전] 대전시립청소년합창단 기획 연주회, 가곡시리즈 Ⅲ. 노래로 보내는 편지",
    programStatus: "공연예정",
    officialUrl: "https://tickets.interpark.com/goods/26011691",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "violet",
    iconPath: "/markers/icon_music.png",
    imageAlt: "대전시립청소년합창단 노래로 보내는 편지 공식 공연 포스터",
    imageUrl: "https://www.culture.go.kr/upload/rdf/26/08/rdf_2026082121181740049.gif",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    eventStart: "2026-09-19T00:00:00+09:00",
    eventEnd: "2026-09-19T23:59:59+09:00",
    eventLocation: "대전예술의전당 앙상블홀",
    intro: [
      "대전에서 부담이 비교적 적은 가격의 합창 공연을 찾는다면 날짜와 공연장을 먼저 확인해 보세요. 대전시립청소년합창단의 가곡시리즈 Ⅲ 《노래로 보내는 편지》는 2026년 9월 19일 대전예술의전당 앙상블홀에서 열리는 것으로 공개되어 있습니다.",
      "등록된 관람료는 전석 5,000원입니다. 공연 시작 시각, 관람 가능 연령, 좌석 위치와 할인 조건은 예매 화면의 최신 안내가 최종 기준이므로 결제 직전에 다시 확인하는 편이 안전합니다.",
    ],
    facts: [
      { label: "장소", value: "대전 서구 대전예술의전당 앙상블홀" },
      { label: "공연일", value: "2026년 9월 19일" },
      { label: "유형", value: "가곡·합창 콘서트" },
      { label: "관람료", value: "전석 5,000원" },
      { label: "상태", value: "공연예정" },
      { label: "문의", value: "대전시립청소년합창단 042-270-8372~4" },
    ],
    takeaway: "대전 서구에서 5천원 합창 공연을 찾는 관객에게 맞는 하루 공연입니다. 실제 시작 시각과 좌석·입장 조건은 공식 예매 안내에서 최종 확인하세요.",
    sections: [
      {
        heading: "가곡 합창은 가사와 화음의 거리를 함께 들어보세요",
        paragraphs: [
          "가곡 공연은 익숙한 선율을 찾는 것만큼 여러 성부가 같은 문장을 어떻게 나누는지 듣는 재미가 있습니다. 첫 곡에서는 전체 화음을 듣고 다음 곡에서는 한 성부의 움직임이나 반주와 목소리가 만나는 지점을 따라가 보세요.",
          "공연 제목처럼 노래가 누군가에게 보내는 편지라고 생각하면 가사의 화자와 받는 사람을 상상하기 쉽습니다. 사전 지식이 없어도 곡마다 떠오른 장면을 짧게 적어 두면 관람의 흐름이 선명해집니다.",
        ],
      },
      {
        heading: "예매 전에 확인할 다섯 가지",
        paragraphs: ["공개 데이터의 날짜와 가격 외 세부 조건은 공식 예매처 안내를 우선해야 합니다."],
        bullets: ["정확한 공연 시작·종료 시각", "관람 연령과 입장 제한", "좌석 지정 여부와 시야", "할인 대상과 증빙 서류", "예매 취소·변경 마감"],
      },
      {
        heading: "대전 9월 저렴한 공연을 찾는 방법",
        paragraphs: [
          "‘대전 9월 합창 공연’, ‘대전예술의전당 5천원 공연’, ‘대전 서구 가곡 콘서트’처럼 지역·시기·가격을 함께 검색하면 비슷한 이름의 다른 공연과 섞이는 일을 줄일 수 있습니다.",
          "공연 당일에는 이동 시간을 여유 있게 잡고 예술의전당의 최신 입장 안내를 확인하세요. 주변 일정은 동네고고 지도에서 거리순으로 비교할 수 있습니다.",
        ],
      },
    ],
    tags: ["대전 9월 합창 공연", "대전예술의전당 5천원 공연", "대전 청소년합창단", "노래로 보내는 편지"],
  },
  {
    slug: "incheon-art-platform-summer-vacation-guide",
    title: "인천아트플랫폼 취향발견 썸머바캉스, 워크숍 확인 가이드",
    seoTitle: "인천아트플랫폼 취향발견 썸머바캉스 일정·비용 | 동네고고",
    description: "인천아트플랫폼에서 진행되는 취향발견 썸머바캉스의 기간, 장소와 워크숍별 비용·예약 확인 방법을 정리했습니다.",
    dek: "여러 워크숍이 묶인 프로젝트는 행사 전체 기간보다 내가 참여할 회차의 대상, 비용과 예약 마감을 따로 확인해야 합니다.",
    category: "문화·전시",
    region: "인천 제물포구",
    audience: "문화예술 워크숍 참여자",
    readingMinutes: 4,
    publishedAt: "2026-08-26T06:38:00+09:00",
    modifiedAt: "2026-08-26T06:38:00+09:00",
    sourceCheckedAt: "2026-08-26",
    programId: "program:cultureinfo_events:31adcc67674e3652",
    programName: "2026 인천아트플랫폼 지역연계 프로젝트 컬쳐컴퍼니 봉봉 《취향발견 썸머바캉스》",
    programStatus: "진행중",
    officialUrl: "https://inartplatform.kr/program/view?no=1325",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "violet",
    iconPath: "/markers/icon_art_class.png",
    imageAlt: "인천아트플랫폼 취향발견 썸머바캉스 공식 프로그램 이미지",
    imageUrl: "https://www.culture.go.kr/upload/rdf/26/08/rdf_2026082421183472447.jpg",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    eventStart: "2026-08-22T00:00:00+09:00",
    eventEnd: "2026-09-05T23:59:59+09:00",
    eventLocation: "인천아트플랫폼",
    intro: [
      "인천아트플랫폼의 지역연계 프로젝트 《취향발견 썸머바캉스》는 2026년 8월 22일부터 9월 5일까지 진행되는 것으로 등록되어 있습니다. 하나의 전시만 보는 일정이라기보다 세부 워크숍과 프로그램을 골라 참여하는 방식으로 접근하는 편이 좋습니다.",
      "비용은 워크숍에 따라 다르게 안내되어 있습니다. 관심 있는 회차를 찾았다면 대상 연령, 준비물, 정원, 신청 마감과 실제 진행 공간을 공식 프로그램 페이지에서 각각 확인하세요.",
    ],
    facts: [
      { label: "장소", value: "인천 제물포구 인천아트플랫폼" },
      { label: "운영 기간", value: "2026년 8월 22일~9월 5일" },
      { label: "유형", value: "지역연계 문화예술 프로젝트·워크숍" },
      { label: "비용", value: "워크숍별 상이" },
      { label: "상태", value: "진행중" },
      { label: "신청", value: "세부 회차별 공식 안내 확인" },
    ],
    takeaway: "인천에서 단회 문화예술 체험을 찾는 분에게 유용한 프로젝트입니다. 행사 전체가 아니라 참여하려는 워크숍의 대상·비용·잔여석을 기준으로 선택하세요.",
    sections: [
      {
        heading: "워크숍 묶음은 ‘내가 가능한 한 회차’부터 고르세요",
        paragraphs: [
          "프로젝트 이름이 같아도 세부 워크숍마다 진행 시간과 난이도가 다를 수 있습니다. 먼저 방문 가능한 날짜를 고르고 그 안에서 대상과 활동 내용을 비교하면 선택지가 빠르게 좁혀집니다.",
          "가족이 함께 참여한다면 보호자 동반 여부와 참가 인원 기준을 확인하세요. 개인별 신청인지 한 가족당 한 번 신청인지에 따라 필요한 예약 수가 달라질 수 있습니다.",
        ],
      },
      {
        heading: "신청 전 체크리스트",
        paragraphs: ["워크숍별 세부 정보는 운영기관 페이지의 최신 안내가 최종 기준입니다."],
        bullets: ["회차별 날짜와 시작 시각", "참여 대상과 보호자 동반 조건", "참가비·재료비 포함 여부", "정원과 대기 신청 가능 여부", "취소 시 연락 방법"],
      },
      {
        heading: "인천 문화예술 체험을 구체적으로 찾는 법",
        paragraphs: [
          "‘인천아트플랫폼 8월 워크숍’, ‘제물포구 가족 예술체험’, ‘인천 9월 문화예술 프로그램’처럼 장소·시기·활동 유형을 함께 검색하면 지금 참여 가능한 회차를 찾기 쉽습니다.",
          "동네고고에서는 인천 지역의 전시·공연·교육 프로그램을 함께 비교할 수 있습니다. 마감된 회차가 있다면 같은 기간 주변의 다른 단회 체험도 살펴보세요.",
        ],
      },
    ],
    tags: ["인천아트플랫폼 워크숍", "제물포구 문화예술 체험", "인천 9월 행사", "취향발견 썸머바캉스"],
  },
  {
    slug: "seoul-nowon-kids-career-experience-guide",
    title: "노원 초등 고학년 직업체험 ‘꿈을 JOB아라!’ 신청 가이드",
    seoTitle: "노원 무료 아동 직업체험 꿈을 JOB아라 신청 일정 | 동네고고",
    description: "노원구 초등 고학년 대상 직업체험 꿈을 JOB아라의 무료 운영일, 접수 기간, 장소와 신청 전 확인할 내용을 정리했습니다.",
    dek: "아동 직업체험은 프로그램 이름보다 대상 학년, 접수 시작 시각, 보호자 확인 사항과 실제 활동 시간을 먼저 보는 것이 중요합니다.",
    category: "교육",
    region: "서울 노원구",
    audience: "초등 고학년 아동·보호자",
    readingMinutes: 4,
    publishedAt: "2026-08-26T06:37:00+09:00",
    modifiedAt: "2026-08-26T06:37:00+09:00",
    sourceCheckedAt: "2026-08-26",
    programId: "program:reservations:4ba5c8651ad002da",
    programName: "[아동] 초등 고학년 직업체험 프로그램 '꿈을 JOB아라!'",
    programStatus: "안내중",
    officialUrl: "https://umppa.seoul.go.kr/icare/user/chilProgrm/orgideaExprnCtzn/BD_selectOrgideaExprnCtzn.do?q_progrmCl=1000&q_placeCode=100&q_progrmSn=3313",
    sourceName: "서울시 문화행사 공공서비스예약 정보",
    accent: "lime",
    iconPath: "/markers/icon_digital.png",
    imageAlt: "노원 초등 고학년 직업체험 꿈을 JOB아라 공식 프로그램 이미지",
    imageUrl: "https://umppa.seoul.go.kr/icare/webcontent/icare/upload/orgideaExprnCtznFile/2026/8/24/4cd3e33f-b91b-43a7-b2a8-c4c8b72b55e5.png",
    imageSource: "서울시 문화행사 공공서비스예약 정보",
    eventStart: "2026-09-21T00:00:00+09:00",
    eventEnd: "2026-09-21T23:59:59+09:00",
    eventLocation: "거점 1호 우리동네키움센터 4층 뚝딱방1",
    intro: [
      "서울 노원구에서 초등 고학년을 위한 무료 직업체험을 찾는다면 접수 기간을 먼저 달력에 표시해 두세요. ‘꿈을 JOB아라!’는 2026년 9월 21일 거점 1호 우리동네키움센터에서 진행되는 것으로 안내되어 있습니다.",
      "접수는 8월 31일 오전 10시부터 9월 14일 오후 3시까지로 공개되어 있습니다. 대상 학년, 세부 활동 시간, 보호자 동의와 준비물은 신청 화면의 최신 공지를 확인한 뒤 접수하세요.",
    ],
    facts: [
      { label: "장소", value: "노원구 거점 1호 우리동네키움센터 4층 뚝딱방1" },
      { label: "운영일", value: "2026년 9월 21일" },
      { label: "접수", value: "8월 31일 10:00~9월 14일 15:00" },
      { label: "대상", value: "초등 고학년 아동" },
      { label: "비용", value: "무료" },
      { label: "상태", value: "안내중" },
    ],
    takeaway: "노원구 초등 고학년이 무료로 참여할 수 있는 직업체험 후보입니다. 대상 학년과 실제 시간, 보호자 확인 사항을 공식 신청 화면에서 최종 확인하세요.",
    sections: [
      {
        heading: "직업체험은 결과보다 질문을 준비하면 좋아요",
        paragraphs: [
          "체험 전에 아이가 궁금한 일을 한두 가지 고르게 해 보세요. ‘이 일을 하려면 무엇을 자주 연습하나요?’처럼 구체적인 질문을 준비하면 활동을 단순한 만들기 시간으로 끝내지 않고 직업의 과정과 연결할 수 있습니다.",
          "체험 뒤에는 좋았던 점뿐 아니라 어렵거나 예상과 달랐던 점도 기록해 보세요. 직업에 대한 선호를 정답처럼 결정하기보다 자신의 관심을 발견하는 자료로 남기는 것이 좋습니다.",
        ],
      },
      {
        heading: "보호자가 신청 전에 확인할 항목",
        paragraphs: ["공개 접수 기간 외 세부 운영 조건은 공식 프로그램 안내가 최종 기준입니다."],
        bullets: ["정확한 대상 학년과 정원", "활동 시작·종료 시각", "보호자 동반 또는 귀가 기준", "준비물과 알레르기 등 주의사항", "취소·대기자 전환 방법"],
      },
      {
        heading: "노원 무료 아동 체험을 찾는 검색어",
        paragraphs: [
          "‘노원 초등 고학년 무료 체험’, ‘노원구 9월 직업체험’, ‘우리동네키움센터 아동 프로그램’처럼 지역·대상·비용을 묶어 검색하면 실제 신청 의도에 가까운 결과를 찾을 수 있습니다.",
          "마감되었더라도 동네고고에서 같은 지역의 교육·체험 프로그램을 날짜순으로 비교해 보세요. 프로그램이 끝난 뒤에도 이 글은 지난 프로그램 기록으로 남습니다.",
        ],
      },
    ],
    tags: ["노원 초등 고학년 체험", "노원 무료 직업체험", "우리동네키움센터 프로그램", "꿈을 JOB아라"],
  },
  {
    slug: "yeongam-sanjo-festival-guide",
    title: "영암 김창조 산조 페스티벌 2026, 일정·장소 확인 가이드",
    seoTitle: "2026 영암 김창조 산조 페스티벌 일정·장소 | 동네고고",
    description: "영암 가야금산조테마공원 일대에서 열리는 김창조 산조 페스티벌의 기간, 장소와 방문 전 확인할 공연표·비용 정보를 정리했습니다.",
    dek: "여러 날 열리는 국악 축제는 전체 기간보다 방문일의 공연표, 입장 방식과 귀가 교통편을 함께 확인해야 시간을 알차게 쓸 수 있습니다.",
    category: "문화·전시",
    region: "전남 영암군",
    audience: "국악·지역축제 방문객",
    readingMinutes: 4,
    publishedAt: "2026-08-26T06:36:00+09:00",
    modifiedAt: "2026-08-26T06:36:00+09:00",
    sourceCheckedAt: "2026-08-26",
    programId: "program:cultureinfo_events:00f3d64d372f6b54",
    programName: "2026 김창조 산조 페스티벌",
    programStatus: "공연예정",
    officialUrl: "https://sanjofestival.com/",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "violet",
    iconPath: "/markers/icon_traditional_music.png",
    imageAlt: "2026 김창조 산조 페스티벌 공식 행사 이미지",
    imageUrl: "https://www.culture.go.kr/upload/ucms/oneCltInfo/2026/202608/973a1a92b8894a8ebe5787c507942317.jpg",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    eventStart: "2026-09-11T00:00:00+09:00",
    eventEnd: "2026-09-13T23:59:59+09:00",
    eventLocation: "영암 가야금산조테마공원 일대",
    intro: [
      "영암에서 국악과 지역 이야기를 함께 만나는 행사를 찾는다면 2026 김창조 산조 페스티벌을 살펴볼 수 있습니다. 공개 데이터상 행사는 9월 11일부터 13일까지 가야금산조테마공원 일대에서 열릴 예정입니다.",
      "현재 공개 데이터에는 확정 관람료가 표시되어 있지 않습니다. 방문하려는 날짜의 공연 시간표, 유료·무료 구역, 체험 예약 여부와 교통 안내는 공식 축제 사이트에서 확인하세요.",
    ],
    facts: [
      { label: "장소", value: "전남 영암군 가야금산조테마공원 일대" },
      { label: "행사 기간", value: "2026년 9월 11일~13일" },
      { label: "유형", value: "국악 공연·지역축제" },
      { label: "상태", value: "공연예정" },
      { label: "비용", value: "공식 일정에서 확인 필요" },
      { label: "확인", value: "날짜별 공연표·체험 예약 여부" },
    ],
    takeaway: "영암에서 산조와 국악 공연을 집중해서 보고 싶은 방문객에게 맞는 3일 행사입니다. 방문일의 공연표와 입장·교통 정보를 공식 사이트에서 먼저 확인하세요.",
    sections: [
      {
        heading: "산조 공연은 악기와 장단의 변화를 따라가 보세요",
        paragraphs: [
          "산조는 느린 흐름에서 빠른 흐름으로 이어지며 악기의 음색과 장단이 바뀌는 과정을 듣는 재미가 있습니다. 모든 곡명을 외우기보다 속도가 달라지는 지점과 연주자의 호흡에 귀를 기울여 보세요.",
          "여러 무대가 열리는 축제라면 서로 다른 악기의 산조를 연달아 비교해 보는 것도 좋습니다. 같은 장단이 악기마다 어떻게 다른 표정으로 들리는지 살펴보면 초보 관객도 공연의 차이를 느낄 수 있습니다.",
        ],
      },
      {
        heading: "축제 방문 전 체크리스트",
        paragraphs: ["행사장 운영은 날짜와 날씨에 따라 달라질 수 있으므로 당일 공지를 우선하세요."],
        bullets: ["방문일의 공연 시작 시각과 무대 위치", "무료·유료 프로그램 구분", "체험 사전예약 여부", "우천 시 변경 또는 취소 공지", "주차·셔틀·대중교통과 귀가 시간"],
      },
      {
        heading: "영암 국악 축제를 구체적으로 찾는 방법",
        paragraphs: [
          "‘영암 9월 국악 축제’, ‘가야금산조테마공원 공연’, ‘김창조 산조 페스티벌 일정’처럼 지역·장르·장소를 함께 검색하면 최신 일정에 빠르게 접근할 수 있습니다.",
          "동네고고 지도에서 영암 주변 문화행사를 함께 비교하고 이동 시간을 계산해 보세요. 현장 운영과 공연표는 축제 공식 공지가 최종 기준입니다.",
        ],
      },
    ],
    tags: ["영암 9월 국악 축제", "김창조 산조 페스티벌", "가야금산조테마공원 행사", "전남 국악 공연"],
  },
  {
    slug: "yangpyeong-weekend-art-exhibition-guide",
    title: "양평군립미술관 위캔드아트 결과전시, 1천원 관람 가이드",
    seoTitle: "양평 위캔드아트 결과전시 기간·관람료 | 동네고고",
    description: "양평군립미술관 2026 위캔드아트 결과전시의 기간, 1천원 관람료와 가족 관람 전 확인할 운영 정보를 정리했습니다.",
    dek: "교육의 결과가 전시로 이어지는 자리에서는 완성 작품뿐 아니라 참여자가 어떤 과정을 거쳤는지 살펴보면 관람이 더 풍부해집니다.",
    category: "문화·전시",
    region: "경기 양평군",
    audience: "가족·미술교육 관심 관람객",
    readingMinutes: 4,
    publishedAt: "2026-08-26T06:35:00+09:00",
    modifiedAt: "2026-08-26T06:35:00+09:00",
    sourceCheckedAt: "2026-08-26",
    programId: "program:cultureinfo_events:c82e6bdbf550f778",
    programName: "2026 위캔드아트 결과전시",
    programStatus: "진행중",
    officialUrl: "https://www.ymuseum.org/home/sub02.php?mid=16&uid=244",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "violet",
    iconPath: "/markers/icon_exhibition.png",
    imageAlt: "양평군립미술관 2026 위캔드아트 결과전시 공식 이미지",
    imageUrl: "https://www.culture.go.kr/upload/rdf/26/08/rdf_2026082421183390300.jpg",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    eventStart: "2026-08-22T00:00:00+09:00",
    eventEnd: "2026-09-27T23:59:59+09:00",
    eventLocation: "양평군립미술관",
    intro: [
      "경기 양평에서 가족과 부담 적게 볼 전시를 찾는다면 양평군립미술관의 2026 위캔드아트 결과전시를 살펴볼 수 있습니다. 전시는 8월 22일부터 9월 27일까지 진행되는 것으로 공개되어 있습니다.",
      "등록된 관람료는 1,000원입니다. 실제 운영시간, 휴관일, 할인 대상과 연계 프로그램은 미술관 공식 안내에서 확인하고 방문하세요.",
    ],
    facts: [
      { label: "장소", value: "경기 양평군 양평군립미술관" },
      { label: "전시 기간", value: "2026년 8월 22일~9월 27일" },
      { label: "유형", value: "미술교육 결과전시" },
      { label: "관람료", value: "1,000원" },
      { label: "상태", value: "진행중" },
      { label: "확인", value: "운영시간·휴관일·연계 프로그램" },
    ],
    takeaway: "양평에서 1천원으로 볼 수 있는 미술교육 결과전시입니다. 휴관일과 입장 마감 시각을 확인하고, 작품의 결과와 과정을 함께 살펴보세요.",
    sections: [
      {
        heading: "결과전시는 완성도보다 변화의 흔적을 보세요",
        paragraphs: [
          "교육 결과전시는 한 사람의 대표작을 감상하는 전시와 관람 기준이 다를 수 있습니다. 작품마다 사용한 재료와 표현 방식, 비슷한 주제를 서로 다르게 풀어낸 지점을 찾아보면 참여자의 선택이 보입니다.",
          "아이와 함께 간다면 가장 마음에 드는 작품을 고르게 한 뒤 색, 모양, 재료 중 무엇이 눈에 들어왔는지 물어보세요. 정답을 맞히는 설명보다 자신의 관찰을 말하도록 돕는 편이 좋습니다.",
        ],
      },
      {
        heading: "관람 전에 확인할 항목",
        paragraphs: ["전시 운영 정보는 양평군립미술관 공식 공지가 최종 기준입니다."],
        bullets: ["요일별 운영시간과 휴관일", "마지막 입장 가능 시각", "1천원 관람료의 할인·무료 대상", "사진 촬영과 작품 보호 규정", "연계 해설·체험 프로그램 여부"],
      },
      {
        heading: "양평 가족 전시를 찾는 검색 방법",
        paragraphs: [
          "‘양평 1천원 전시’, ‘양평군립미술관 가족 전시’, ‘양평 9월 미술교육 전시’처럼 지역·비용·대상을 함께 검색하면 방문 목적에 맞는 정보를 찾기 쉽습니다.",
          "전시 기간이 끝나도 이 글은 지난 프로그램 기록으로 보존합니다. 현재 운영 중인 전시는 동네고고에서 양평 지역과 문화·전시 카테고리를 함께 선택해 비교하세요.",
        ],
      },
    ],
    tags: ["양평 1천원 전시", "양평군립미술관 가족 전시", "위캔드아트 결과전시", "양평 9월 전시"],
  },
  {
    slug: "goseong-cultural-arts-academy-guide",
    title: "강원 고성 문화예술 아카데미, 9월 과정 확인 가이드",
    seoTitle: "강원 고성 문화예술 아카데미 일정·신청 가이드 | 동네고고",
    description: "2026 고성 문화예술 아카데미의 운영 기간, 문의처와 신청 전에 확인할 비용·장소·세부 과정 체크리스트를 정리했습니다.",
    dek: "여러 주 이어지는 문화예술 교육은 과정 이름보다 세부 주제와 장소, 참여 가능한 회차를 먼저 확인해야 꾸준히 참여하기 좋습니다.",
    category: "교육",
    region: "강원 고성군",
    audience: "문화예술 교육 관심자",
    readingMinutes: 4,
    publishedAt: "2026-08-25T06:38:00+09:00",
    modifiedAt: "2026-08-25T06:38:00+09:00",
    sourceCheckedAt: "2026-08-25",
    programId: "program:cultureinfo_events:d38d30b212958690",
    programName: "2026 고성 문화예술 아카데미",
    programStatus: "진행중",
    officialUrl: "https://goseongcf.or.kr/notify/998",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "lime",
    iconPath: "/markers/icon_art_class.png",
    imageAlt: "2026 고성 문화예술 아카데미 공식 프로그램 이미지",
    imageUrl: "https://www.culture.go.kr/upload/ucms/oneCltInfo/2026/202608/7a801654f9db4df1aa15e6b043a7d5e0.jpg",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    eventStart: "2026-08-25T00:00:00+09:00",
    eventEnd: "2026-09-29T23:59:59+09:00",
    eventLocation: "강원 고성군(세부 장소 공식 공지 확인)",
    intro: [
      "문화예술 아카데미를 고를 때는 전체 기간만 보는 것보다 어떤 주제를 몇 회에 걸쳐 배우는지, 각 회차의 장소가 같은지를 먼저 확인하는 편이 좋습니다. 2026 고성 문화예술 아카데미는 공개 데이터상 8월 25일부터 9월 29일까지 진행되는 교육·체험 프로그램입니다.",
      "현재 공개 정보에는 세부 장소와 비용이 확정값으로 표시되지 않았습니다. 따라서 참여를 결정하기 전 고성문화재단 공식 공지에서 과정 구성, 모집 대상, 신청 방식과 회차별 장소를 확인해야 합니다. 문의가 필요하면 문화사업팀 안내 번호를 이용할 수 있습니다.",
    ],
    facts: [
      { label: "지역", value: "강원특별자치도 고성군" },
      { label: "운영 기간", value: "2026년 8월 25일~9월 29일" },
      { label: "유형", value: "문화예술 교육·체험" },
      { label: "상태", value: "진행중" },
      { label: "비용", value: "공식 공지에서 확인 필요" },
      { label: "문의", value: "고성문화재단 문화사업팀 033-681-0111" },
    ],
    takeaway: "강원 고성에서 여러 주 이어지는 문화예술 교육을 찾는 분에게 맞는 후보입니다. 세부 과정·장소·비용을 공식 공지에서 확인한 뒤 신청하세요.",
    sections: [
      {
        heading: "여러 주 과정은 회차 구성을 먼저 보세요",
        paragraphs: [
          "아카데미라는 이름 아래 강연, 실습, 현장 체험이 함께 묶일 수 있습니다. 모든 회차가 같은 대상에게 열리는지, 일부 회차만 선택할 수 있는지에 따라 실제 참여 계획이 달라집니다. 공식 공지의 날짜별 표를 확인하고 참석 가능한 회차를 달력에 먼저 표시해 보세요.",
          "퇴근 뒤 또는 다른 지역에서 이동한다면 수업 시작 시각뿐 아니라 귀가 교통편도 함께 계산해야 합니다. 장소가 회차마다 바뀌는 과정이라면 첫날 장소만 저장하지 말고 각 회차 안내를 별도로 확인하는 편이 안전합니다.",
        ],
      },
      {
        heading: "신청 전에 확인할 항목",
        paragraphs: ["공개 데이터만으로 확정되지 않은 정보는 운영기관 안내가 최종 기준입니다. 아래 항목을 한 번에 문의하면 재확인 시간을 줄일 수 있습니다."],
        bullets: ["모집 대상과 지역 거주 요건", "과정별 정원과 신청 마감일", "회차별 장소·시작 시각", "수강료와 재료비 포함 여부", "결석 또는 중도 취소 기준"],
      },
      {
        heading: "고성 문화예술 강좌를 찾는 검색 방법",
        paragraphs: [
          "‘강원 고성 문화예술 강좌’, ‘고성군 9월 예술교육’, ‘고성문화재단 아카데미’처럼 지역·시기·운영기관을 함께 검색하면 비슷한 이름의 다른 지역 프로그램과 섞이는 일을 줄일 수 있습니다.",
          "동네고고에서는 교육·문화 카테고리와 위치를 함께 비교할 수 있습니다. 이번 과정의 세부 정보가 맞지 않으면 같은 기간 주변의 단회 체험이나 전시 연계 교육도 함께 살펴보세요.",
        ],
      },
    ],
    tags: ["강원 고성 문화예술 강좌", "고성문화재단 아카데미", "고성군 9월 교육", "문화예술 체험"],
  },
  {
    slug: "daegu-harmonica-orchestra-concert-guide",
    title: "대구 하모니카 오케스트라 정기연주회, 아양홀 관람 가이드",
    seoTitle: "대구 하모니카 오케스트라 정기연주회 일정·예매 | 동네고고",
    description: "대구 아양아트센터에서 열리는 제22회 하모니카 오케스트라 정기연주회의 날짜, 관람료와 예매 전 확인할 내용을 정리했습니다.",
    dek: "하루만 열리는 정기연주회는 날짜보다 실제 시작 시각과 좌석, 취소 규정을 먼저 확인해야 관람 계획을 정확히 세울 수 있습니다.",
    category: "문화·전시",
    region: "대구 동구",
    audience: "음악·하모니카 관객",
    readingMinutes: 4,
    publishedAt: "2026-08-25T06:37:00+09:00",
    modifiedAt: "2026-08-25T06:37:00+09:00",
    sourceCheckedAt: "2026-08-25",
    programId: "program:cultureinfo_events:d199d58c5fdfbb87",
    programName: "(사)한국하모니카리더스 제22회 대구하모니카오케스트라 정기연주회",
    programStatus: "공연예정",
    officialUrl: "https://tickets.interpark.com/goods/26011793",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "violet",
    iconPath: "/markers/icon_music.png",
    imageAlt: "제22회 대구 하모니카 오케스트라 정기연주회 공식 포스터",
    imageUrl: "https://www.culture.go.kr/upload/ucms/oneCltInfo/2026/202608/f959e6a7386b4748ba93c9e6e0620741.jpg",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    eventStart: "2026-09-12T00:00:00+09:00",
    eventEnd: "2026-09-12T23:59:59+09:00",
    eventLocation: "아양아트센터 아양홀",
    intro: [
      "오케스트라 공연은 익숙한 악기 편성과 다른 음색을 한 자리에서 비교해 듣는 재미가 있습니다. 제22회 대구 하모니카 오케스트라 정기연주회는 2026년 9월 12일 대구 동구 아양아트센터 아양홀에서 열리는 것으로 등록되어 있습니다.",
      "공개 정보의 관람료는 전석 10,000원입니다. 하루 공연은 다른 날짜로 옮기기 어려우므로 예매 전에 실제 시작 시각, 러닝타임, 관람 연령과 좌석 배치도를 공식 예매 화면에서 확인하세요.",
    ],
    facts: [
      { label: "장소", value: "대구 동구 아양아트센터 아양홀" },
      { label: "공연일", value: "2026년 9월 12일" },
      { label: "유형", value: "음악·콘서트" },
      { label: "관람료", value: "전석 10,000원" },
      { label: "상태", value: "공연예정" },
      { label: "문의", value: "010-9311-2121" },
    ],
    takeaway: "대구에서 부담이 비교적 적은 가격의 기악 공연을 찾는 관객에게 맞는 하루 공연입니다. 시작 시각과 좌석을 예매 화면에서 최종 확인하세요.",
    sections: [
      {
        heading: "하모니카 오케스트라는 무엇을 들으면 좋을까요",
        paragraphs: [
          "하모니카는 크기가 작지만 음역과 역할에 따라 여러 파트로 나뉠 수 있습니다. 멜로디만 따라가기보다 낮은 음을 받치는 파트와 리듬을 만드는 파트가 어떻게 교차하는지 들어보면 합주의 층이 더 잘 느껴집니다.",
          "곡을 미리 알지 못해도 괜찮습니다. 첫 곡에서는 전체 소리를 듣고, 다음 곡에서는 한 파트의 움직임을 골라 따라가 보세요. 같은 편성이 곡마다 어떻게 다른 색을 만드는지 비교하는 것만으로도 충분한 관람 기준이 됩니다.",
        ],
      },
      {
        heading: "예매 전 체크리스트",
        paragraphs: ["등록된 날짜와 가격 외의 세부 조건은 예매 페이지 안내를 우선해야 합니다."],
        bullets: ["공연 시작·종료 시각", "관람 연령과 입장 제한", "좌석 지정 여부와 시야", "예매 취소·변경 마감", "아양아트센터 주차와 대중교통 동선"],
      },
      {
        heading: "대구 9월 음악 공연을 함께 찾는 법",
        paragraphs: [
          "‘대구 9월 하모니카 공연’, ‘아양아트센터 1만원 콘서트’, ‘대구 동구 주말 연주회’처럼 지역·가격·장르를 함께 넣으면 관람 의도에 맞는 정보를 빠르게 찾을 수 있습니다.",
          "공연 전후 일정까지 계획한다면 동네고고 지도에서 아양아트센터 주변 프로그램과 이동 시간을 함께 확인해 보세요. 당일 운영 정보는 공연장과 예매처 공지가 최종 기준입니다.",
        ],
      },
    ],
    tags: ["대구 하모니카 공연", "아양아트센터 연주회", "대구 9월 콘서트", "하모니카 오케스트라"],
  },
  {
    slug: "busan-merge-coexistence-exhibition-guide",
    title: "부산 금정구 무료 전시, 《공존의 경계에 흐르다》 관람 가이드",
    seoTitle: "부산 금정구 무료 전시 공존의 경계에 흐르다 | 동네고고",
    description: "부산 복합문화예술공간 MERGE에서 열리는 무료 전시의 기간, 위치와 관람 전에 확인할 운영 정보를 정리했습니다.",
    dek: "짧은 기간 열리는 전시는 작품 설명을 미리 외우기보다 운영일과 입장 시간, 공간 위치를 정확히 확인하는 것이 먼저입니다.",
    category: "문화·전시",
    region: "부산 금정구",
    audience: "현대미술 관람객",
    readingMinutes: 4,
    publishedAt: "2026-08-25T06:36:00+09:00",
    modifiedAt: "2026-08-25T06:36:00+09:00",
    sourceCheckedAt: "2026-08-25",
    programId: "program:cultureinfo_events:188122242742c722",
    programName: "공존의 경계에 흐르다: 파괴와 생성, 그리고 시선의 궤적",
    programStatus: "공연예정",
    officialUrl: "https://blog.naver.com/openartsmerge/224387415861",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "violet",
    iconPath: "/markers/icon_exhibition.png",
    imageAlt: "부산 공존의 경계에 흐르다 공식 전시 이미지",
    imageUrl: "https://www.culture.go.kr/upload/ucms/oneCltInfo/2026/202608/d2ad1a5c1f674223b9c341b0ad4b2613.jpg",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    eventStart: "2026-09-01T00:00:00+09:00",
    eventEnd: "2026-09-10T23:59:59+09:00",
    eventLocation: "복합문화예술공간 MERGE",
    intro: [
      "부산 금정구에서 무료 현대미술 전시를 찾는다면 전시 기간과 공간의 실제 운영시간을 함께 봐야 합니다. 《공존의 경계에 흐르다: 파괴와 생성, 그리고 시선의 궤적》은 복합문화예술공간 MERGE에서 9월 1일부터 10일까지 열리는 것으로 등록되어 있습니다.",
      "관람료는 무료로 안내되어 있지만 휴관일, 마지막 입장 시각과 별도 예약 여부는 공식 안내에서 다시 확인해야 합니다. 전시 기간이 열흘로 비교적 짧아 방문일을 미루기보다 가능한 날짜를 먼저 정해 두는 편이 좋습니다.",
    ],
    facts: [
      { label: "장소", value: "부산 금정구 복합문화예술공간 MERGE" },
      { label: "주소", value: "부산 금정구 부산대학로50번길 49 1층" },
      { label: "전시 기간", value: "2026년 9월 1일~10일" },
      { label: "유형", value: "현대미술 전시" },
      { label: "비용", value: "무료" },
      { label: "문의", value: "051-527-8196" },
    ],
    takeaway: "부산대 인근에서 무료로 볼 수 있는 단기 전시입니다. 방문 당일 운영시간과 휴관 여부를 확인한 뒤 이동하세요.",
    sections: [
      {
        heading: "제목을 관람 질문으로 바꿔 보세요",
        paragraphs: [
          "전시 제목의 ‘파괴와 생성’, ‘시선의 궤적’ 같은 표현을 미리 해석할 필요는 없습니다. 대신 어떤 장면에서 무언가가 사라지거나 새로 생기는 느낌을 받았는지, 시선이 어디에서 멈췄는지를 관람 중 질문으로 남겨 보세요.",
          "한 작품을 오래 봐도 되고 전체 공간을 먼저 둘러봐도 됩니다. 첫 바퀴에는 마음이 가는 작품을 고르고, 두 번째에는 처음 지나친 작품을 다시 보는 방식이 작은 전시 공간을 부담 없이 경험하는 데 도움이 됩니다.",
        ],
      },
      {
        heading: "방문 전에 확인할 네 가지",
        paragraphs: ["무료 전시도 공간 운영 사정에 따라 입장 조건이 달라질 수 있습니다."],
        bullets: ["요일별 운영시간과 휴관일", "마지막 입장 가능 시각", "별도 예약 또는 단체 관람 제한", "사진 촬영과 작품 보호 규정"],
      },
      {
        heading: "부산 금정구 전시 검색을 좁히는 방법",
        paragraphs: [
          "‘부산 금정구 무료 전시’, ‘부산대 9월 현대미술’, ‘MERGE 전시 일정’처럼 지역·비용·시기를 함께 검색하면 현재 관람 가능한 후보를 찾기 쉽습니다.",
          "관람 뒤에는 가장 오래 머문 작품과 그 이유를 한 문장으로 남겨 보세요. 전시 설명을 그대로 옮기기보다 자신이 실제로 본 장면을 기록하면 짧은 방문도 오래 기억할 수 있습니다.",
        ],
      },
    ],
    tags: ["부산 금정구 무료 전시", "부산대 현대미술", "MERGE 전시", "부산 9월 전시"],
  },
  {
    slug: "gangjin-hamaek-festival-guide",
    title: "강진 하맥축제 2026, 6인 예약석 가격과 일정 확인 가이드",
    seoTitle: "2026 강진 하맥축제 일정·예약석 가격 가이드 | 동네고고",
    description: "제4회 강진 하맥축제의 행사 기간, 장소, 6인 사전예약석 가격과 방문 전에 확인할 교통·입장 정보를 정리했습니다.",
    dek: "여러 날 열리는 야외 축제는 입장권만 보기보다 방문일의 공연 시간표, 우천 공지와 귀가 교통편을 함께 확인해야 합니다.",
    category: "문화·전시",
    region: "전남 강진군",
    audience: "축제·공연 방문객",
    readingMinutes: 4,
    publishedAt: "2026-08-25T06:35:00+09:00",
    modifiedAt: "2026-08-25T06:35:00+09:00",
    sourceCheckedAt: "2026-08-25",
    programId: "program:cultureinfo_events:9b043f7e2ff23da6",
    programName: "제4회 강진하맥축제",
    programStatus: "공연예정",
    officialUrl: "https://www.ticketlink.co.kr/product/64593",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "violet",
    iconPath: "/markers/icon_festival.png",
    imageAlt: "제4회 강진 하맥축제 공식 행사 이미지",
    imageUrl: "https://www.culture.go.kr/upload/rdf/26/07/rdf_2026072821171017382.png",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    eventStart: "2026-08-27T00:00:00+09:00",
    eventEnd: "2026-08-29T23:59:59+09:00",
    eventLocation: "강진종합운동장",
    intro: [
      "제4회 강진 하맥축제는 공개 데이터상 2026년 8월 27일부터 29일까지 강진종합운동장에서 열리는 음악·축제 프로그램입니다. 여러 날 이어지는 행사이므로 전체 기간보다 내가 방문할 날짜의 무대 일정과 입장 시간을 따로 확인해야 합니다.",
      "공개 정보에는 6인 사전예약석이 150,000원으로 표시되어 있습니다. 이 금액이 일반 입장 조건과 같은지는 단정할 수 없으므로 예매 화면에서 좌석 구성, 포함 혜택, 취소 규정과 현장 입장 방식을 최종 확인하세요.",
    ],
    facts: [
      { label: "장소", value: "전남 강진군 강진종합운동장" },
      { label: "행사 기간", value: "2026년 8월 27일~29일" },
      { label: "유형", value: "음악·지역 축제" },
      { label: "예약석", value: "6인 사전예약석 150,000원으로 공개" },
      { label: "상태", value: "공연예정" },
      { label: "문의", value: "061-430-3357" },
    ],
    takeaway: "강진의 여름 야외 축제를 찾는 방문객에게 맞는 행사입니다. 방문일 공연표와 6인 예약석 포함 내용을 공식 예매 화면에서 확인하세요.",
    sections: [
      {
        heading: "여러 날 축제는 날짜별 시간표가 핵심이에요",
        paragraphs: [
          "같은 축제라도 날짜마다 출연진과 시작 시각이 다를 수 있습니다. 보고 싶은 무대가 있다면 행사 전체 기간이 아니라 해당 날짜의 공연표를 저장하고, 입장 대기 시간을 포함해 도착 목표 시각을 정하세요.",
          "야외 행사는 날씨에 따라 일정이나 입장 방식이 달라질 수 있습니다. 출발 당일 공식 공지에서 우천 대응, 반입 제한 물품, 주차장과 셔틀 운영 여부를 다시 확인하는 것이 좋습니다.",
        ],
      },
      {
        heading: "6인 예약석 결제 전 체크리스트",
        paragraphs: ["공개된 가격만으로 좌석의 상세 구성과 혜택을 판단하지 말고 예매 상품 설명을 기준으로 비교하세요."],
        bullets: ["6인이 함께 입장해야 하는지", "좌석 위치와 테이블 제공 여부", "일반 입장권 또는 별도 이용권 포함 여부", "부분 취소·양도 가능 여부", "예매 수수료와 취소 마감"],
      },
      {
        heading: "강진 축제를 찾는 롱테일 검색어",
        paragraphs: [
          "‘강진 8월 축제’, ‘강진 하맥축제 6인 예약석’, ‘강진종합운동장 공연 일정’처럼 지역·시기·궁금한 조건을 함께 검색하면 가격 정보만 반복되는 결과에서 벗어나기 쉽습니다.",
          "멀리서 방문한다면 공연 종료 시각 뒤 대중교통과 숙박 동선을 먼저 확인하세요. 동네고고 지도에서는 행사장 주변 프로그램과 거리를 함께 살펴볼 수 있습니다.",
        ],
      },
    ],
    tags: ["강진 8월 축제", "강진 하맥축제", "강진종합운동장 행사", "하맥축제 예약석"],
  },
  {
    slug: "seoul-science-museum-plant-atelier-guide",
    title: "서울시립과학관 성인교육, 식물 관찰과 표본 수업 확인 가이드",
    seoTitle: "서울시립과학관 식물 아뜰리에 성인교육 일정 | 동네고고",
    description: "서울시립과학관 성인교육 식물 아뜰리에의 운영 기간, 문의처와 신청 전에 확인할 회차·재료비·준비물 정보를 정리했습니다.",
    dek: "식물 관찰과 표본 제작을 함께 배우는 과정은 수업 횟수, 재료 제공 범위와 결과물 보관 방법을 확인하면 선택하기 쉬워집니다.",
    category: "교육",
    region: "서울 노원구",
    audience: "성인·식물 관찰 입문자",
    readingMinutes: 4,
    publishedAt: "2026-08-25T06:34:00+09:00",
    modifiedAt: "2026-08-25T06:34:00+09:00",
    sourceCheckedAt: "2026-08-25",
    programId: "program:cultureinfo_events:4a4485f1b9b7f2b4",
    programName: "[서울시립과학관] 2026 과학관 성인교육 '식물 아뜰리에: 관찰과 표본'",
    programStatus: "공연예정",
    officialUrl: "https://science.seoul.go.kr/sciEdu/adultScience/read?menuId=72&progMstId=2198",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "lime",
    iconPath: "/markers/icon_craft.png",
    imageAlt: "서울시립과학관 식물 아뜰리에 공식 교육 이미지",
    imageUrl: "https://www.culture.go.kr/upload/ucms/oneCltInfo/2026/202608/fcf3eb8ebb514a8e9843753364ca5a7f.jpg",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    eventStart: "2026-09-01T00:00:00+09:00",
    eventEnd: "2026-09-15T23:59:59+09:00",
    eventLocation: "서울시립과학관(세부 강의실 확인 필요)",
    intro: [
      "식물 관찰 수업은 이름을 외우는 강의보다 잎과 줄기, 표면의 차이를 직접 살펴보는 과정에서 재미가 생깁니다. 서울시립과학관의 성인교육 ‘식물 아뜰리에: 관찰과 표본’은 2026년 9월 1일부터 15일까지 운영되는 것으로 등록되어 있습니다.",
      "공개 데이터에는 세부 시간과 비용이 확정값으로 담겨 있지 않습니다. 공식 교육 안내에서 신청 기간, 실제 수업 회차, 재료비와 준비물을 확인하고, 표본 제작 결과물을 가져갈 수 있는지도 함께 살펴보세요.",
    ],
    facts: [
      { label: "운영기관", value: "서울시립과학관" },
      { label: "지역", value: "서울 노원구" },
      { label: "운영 기간", value: "2026년 9월 1일~15일" },
      { label: "유형", value: "성인 과학교육·식물 관찰" },
      { label: "비용", value: "공식 교육 안내에서 확인 필요" },
      { label: "문의", value: "02-970-4581" },
    ],
    takeaway: "서울에서 식물 관찰과 표본 제작을 배우고 싶은 성인에게 맞는 과정입니다. 회차·재료비·준비물을 공식 안내에서 확인하세요.",
    sections: [
      {
        heading: "관찰 수업은 결과보다 기록 방법이 중요해요",
        paragraphs: [
          "같은 식물을 보더라도 크기만 적는 것과 잎맥, 가장자리, 표면의 질감을 함께 기록하는 것은 전혀 다른 관찰이 됩니다. 첫 수업 전 작은 노트에 ‘형태·색·촉감·냄새’처럼 확인할 항목을 만들어 두면 강의 내용을 따라가기 쉽습니다.",
          "표본 제작은 채집 대상과 보존 방법에 따라 주의할 점이 다를 수 있습니다. 임의로 식물을 채집하기보다 수업에서 제공하거나 허용한 재료만 사용하고, 완성품의 보관 조건을 강사에게 확인하세요.",
        ],
      },
      {
        heading: "신청 전에 물어볼 내용",
        paragraphs: ["성인 대상 과정도 입문 수준과 작업 시간이 다양하므로 아래 조건을 확인하면 좋습니다."],
        bullets: ["총 회차와 회차별 수업 시간", "초보자 참여 가능 여부", "재료비와 도구 제공 범위", "개인 준비물과 복장", "표본 결과물 수령·보관 방법"],
      },
      {
        heading: "서울 성인 과학 강좌를 찾는 방법",
        paragraphs: [
          "‘서울 성인 식물 관찰 수업’, ‘노원구 9월 과학 강좌’, ‘서울시립과학관 표본 만들기’처럼 대상·지역·활동을 함께 검색하면 어린이 과정과 구분하기 쉽습니다.",
          "이번 일정이 맞지 않는다면 동네고고에서 교육·취미 카테고리를 함께 보고 과학관, 식물원, 도서관의 단회 체험도 비교해 보세요. 신청 상태는 운영기관 화면을 최종 기준으로 확인해야 합니다.",
        ],
      },
    ],
    tags: ["서울 성인 식물 관찰", "서울시립과학관 교육", "노원구 9월 강좌", "식물 표본 수업"],
  },
  {
    slug: "gwangmyeong-peter-pan-musical-guide",
    title: "광명 피터팬 뮤지컬, 아이와 관람 전 확인할 일정과 좌석",
    seoTitle: "광명 아이와 피터팬 뮤지컬 일정·예매 가이드 | 동네고고",
    description: "광명 소나무예술극장 피터팬 뮤지컬의 공연 기간, 관람료, 장소와 아이 동반 관람 전 확인할 내용을 정리했습니다.",
    dek: "익숙한 피터팬 이야기를 무대에서 만날 때, 아이의 첫 공연 경험을 편안하게 만드는 준비 항목을 먼저 살펴보세요.",
    category: "문화·전시",
    region: "경기 광명시",
    audience: "아이 동반 가족",
    readingMinutes: 4,
    publishedAt: "2026-08-24T06:44:00+09:00",
    modifiedAt: "2026-08-24T06:44:00+09:00",
    sourceCheckedAt: "2026-08-24",
    programId: "program:cultureinfo_events:a4c55b2031cfae0e",
    programName: "[광명] 피터팬",
    programStatus: "공연예정",
    officialUrl: "https://booking.naver.com/booking/5/bizes/563361",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "violet",
    iconPath: "/markers/icon_theater.png",
    imageAlt: "광명 소나무예술극장 피터팬 공식 공연 이미지",
    imageUrl: "https://www.culture.go.kr/upload/rdf/26/08/rdf_2026081921172670323.jpg",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    eventStart: "2026-08-29T00:00:00+09:00",
    eventEnd: "2026-10-11T23:59:59+09:00",
    eventLocation: "소나무예술극장",
    intro: [
      "아이와 뮤지컬을 고를 때는 유명한 이야기인지보다 공연 시간이 아이의 생활 리듬과 맞는지, 관람 연령과 좌석 규정이 명확한지를 먼저 확인하는 편이 좋습니다. 광명 소나무예술극장에서 예정된 피터팬은 2026년 8월 29일부터 10월 11일까지로 등록된 가족 공연입니다.",
      "동네고고가 8월 24일 확인한 공개 정보의 관람료는 전석 17,000원입니다. 날짜 범위 안의 실제 공연 요일과 회차, 잔여 좌석은 예매 화면에서 달라질 수 있으므로 방문일을 정한 뒤 회차별 정보를 다시 확인하세요.",
    ],
    facts: [
      { label: "장소", value: "경기 광명시 소나무예술극장" },
      { label: "공연 기간", value: "2026년 8월 29일~10월 11일" },
      { label: "분류", value: "뮤지컬·오페라" },
      { label: "관람료", value: "전석 17,000원" },
      { label: "현재 상태", value: "공연예정" },
      { label: "예매", value: "네이버 예약 공식 화면에서 회차 확인" },
    ],
    takeaway: "광명에서 아이와 볼 뮤지컬을 찾는 가족에게 적합한 후보입니다. 관람 연령, 실제 회차와 좌석을 예매 화면에서 확인한 뒤 결정하세요.",
    sections: [
      {
        heading: "첫 가족 뮤지컬은 이야기보다 회차가 중요해요",
        paragraphs: [
          "아이에게 익숙한 피터팬이라도 낮잠이나 식사 시간과 겹치면 공연에 집중하기 어렵습니다. 이동 시간을 포함해 공연장 도착 시각을 계산하고, 시작 20~30분 전 여유 있게 입장할 수 있는 회차를 고르세요.",
          "같은 기간의 공연도 평일과 주말 운영 회차가 다를 수 있습니다. 전체 기간만 보고 출발하지 말고 예매 가능한 날짜와 시작 시각을 한 번 더 확인해야 합니다.",
        ],
      },
      {
        heading: "아이와 예매하기 전 체크리스트",
        paragraphs: ["공개 데이터에는 작품명과 기간, 가격이 표시되어 있습니다. 실제 관람 조건은 회차별 공식 안내가 최종 기준입니다."],
        bullets: ["권장·제한 관람 연령", "아동도 별도 좌석권이 필요한지", "공연 시간과 인터미션 유무", "취소·변경 수수료와 지연 입장 규정"],
      },
      {
        heading: "광명 가족 공연을 더 정확히 찾는 검색법",
        paragraphs: [
          "‘광명 아이와 뮤지컬’, ‘광명 주말 피터팬 공연’, ‘소나무예술극장 어린이 공연’처럼 지역·동반 대상·작품 유형을 함께 검색하면 원하는 회차를 더 빨리 찾을 수 있습니다.",
          "공연이 끝난 뒤에는 아이에게 기억나는 장면 한 가지를 묻고 이야기를 이어 보세요. 정답을 설명하기보다 아이가 본 무대의 색과 움직임을 말하게 하면 첫 공연의 기억이 오래 남습니다.",
        ],
      },
    ],
    tags: ["광명 아이와 뮤지컬", "광명 피터팬", "소나무예술극장", "광명 어린이 공연"],
  },
  {
    slug: "daegu-helium-dance-performance-guide",
    title: "대구 헬리움 무용 공연, 팔공홀 관람 전 확인할 일정과 좌석",
    seoTitle: "대구 팔공홀 헬리움 무용 공연 일정·예매 가이드 | 동네고고",
    description: "대구문화예술회관 팔공홀의 헬리움 HELIUM 무용 공연 날짜, 좌석별 가격과 관람 전 확인할 내용을 정리했습니다.",
    dek: "현대무용을 처음 보는 관객도 공연 정보와 좌석, 이동 시간을 미리 정리하면 작품에 더 편안하게 집중할 수 있습니다.",
    category: "문화·전시",
    region: "대구 달서구",
    audience: "무용·공연 관람객",
    readingMinutes: 4,
    publishedAt: "2026-08-24T06:43:00+09:00",
    modifiedAt: "2026-08-24T06:43:00+09:00",
    sourceCheckedAt: "2026-08-24",
    programId: "program:cultureinfo_events:80315bdd9019d4c3",
    programName: "[대구] 이준욱 도도무브댄스시어터 헬리움HELIUM",
    programStatus: "공연예정",
    officialUrl: "https://tickets.interpark.com/goods/26008988",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "violet",
    iconPath: "/markers/icon_theater.png",
    imageAlt: "대구 헬리움 HELIUM 공식 무용 공연 이미지",
    imageUrl: "https://www.culture.go.kr/upload/rdf/26/07/rdf_2026072721193560505.gif",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    eventStart: "2026-08-26T00:00:00+09:00",
    eventEnd: "2026-08-26T23:59:59+09:00",
    eventLocation: "대구문화예술회관 팔공홀",
    intro: [
      "현대무용은 줄거리를 미리 외우기보다 움직임과 음악, 무대 공간이 어떻게 달라지는지 관찰하면 처음 보는 관객도 부담 없이 즐길 수 있습니다. 헬리움 HELIUM은 대구문화예술회관 팔공홀에서 2026년 8월 26일 공연 예정으로 등록되어 있습니다.",
      "공개 정보의 좌석 가격은 R석 30,000원, S석 20,000원입니다. 실제 시작 시각과 러닝타임, 관람 연령, 좌석별 잔여 수량은 공식 예매 페이지에서 최종 확인하세요.",
    ],
    facts: [
      { label: "장소", value: "대구문화예술회관 팔공홀" },
      { label: "공연일", value: "2026년 8월 26일" },
      { label: "분류", value: "무용·발레" },
      { label: "좌석 가격", value: "R석 30,000원 · S석 20,000원" },
      { label: "현재 상태", value: "공연예정" },
      { label: "문의", value: "010-4473-3299" },
    ],
    takeaway: "대구 달서구에서 현대무용 공연을 찾는 관객에게 맞는 하루 공연입니다. 시작 시각과 관람 연령을 공식 예매 화면에서 꼭 확인하세요.",
    sections: [
      {
        heading: "현대무용을 처음 볼 때 좋은 관람 기준",
        paragraphs: [
          "무용 공연은 모든 장면의 의미를 해석하려 하기보다 반복되는 동작, 무대의 거리와 속도 변화를 따라가면 훨씬 편안합니다. 공연 전에 작품 제목에서 떠오르는 이미지를 한 가지 생각해 두고 무대에서 어떻게 달라지는지 비교해 보세요.",
          "좌석 등급을 고를 때는 가격만 아니라 무대 전체를 보고 싶은지, 무용수의 세밀한 움직임을 가까이 보고 싶은지를 함께 고려하는 것이 좋습니다.",
        ],
      },
      {
        heading: "팔공홀 도착 전에 확인할 네 가지",
        paragraphs: ["당일 현장 상황은 공개 데이터보다 공식 예매·공연장 안내가 더 빠르게 갱신될 수 있습니다."],
        bullets: ["정확한 시작 시각과 러닝타임", "관람 연령과 지연 입장 가능 여부", "선택 좌석의 시야와 취소 수수료", "대구문화예술회관 입구와 공연장 이동 시간"],
      },
      {
        heading: "대구 무용 공연 검색 의도를 좁히는 방법",
        paragraphs: [
          "‘대구 현대무용 공연’, ‘달서구 팔공홀 8월 공연’, ‘대구문화예술회관 무용’처럼 지역·장르·월을 함께 입력하면 비슷한 행사와 비교하기 쉽습니다.",
          "공연 전후 시간을 넉넉하게 잡고 같은 장소의 전시나 주변 문화 공간을 함께 살펴보면 한 번의 이동으로 더 풍성한 문화 일정을 만들 수 있습니다.",
        ],
      },
    ],
    tags: ["대구 현대무용 공연", "팔공홀 헬리움", "달서구 8월 공연", "대구문화예술회관"],
  },
  {
    slug: "gimje-cosette-musical-guide",
    title: "김제 레미제라블 코제트 뮤지컬, 5천원 공연 관람 가이드",
    seoTitle: "김제 5천원 뮤지컬 코제트 소녀이야기 일정·예매 | 동네고고",
    description: "김제문화예술회관 레미제라블 코제트 소녀이야기의 공연일, 5천원 관람료와 가족 관람 전 확인할 항목을 정리했습니다.",
    dek: "부담 낮은 가격의 지역 공연도 관람 연령과 실제 회차를 먼저 확인하면 가족의 하루 일정에 더 잘 맞출 수 있습니다.",
    category: "문화·전시",
    region: "전북 김제시",
    audience: "가족·뮤지컬 관람객",
    readingMinutes: 4,
    publishedAt: "2026-08-24T06:42:00+09:00",
    modifiedAt: "2026-08-24T06:42:00+09:00",
    sourceCheckedAt: "2026-08-24",
    programId: "program:cultureinfo_events:a72d69ca51739fb0",
    programName: "[김제] 레미제라블 코제트 소녀이야기",
    programStatus: "공연예정",
    officialUrl: "https://www.ticketlink.co.kr/product/64813",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "violet",
    iconPath: "/markers/icon_theater.png",
    imageAlt: "김제 레미제라블 코제트 소녀이야기 공식 공연 이미지",
    imageUrl: "https://www.culture.go.kr/upload/rdf/26/08/rdf_2026082021172213460.jpg",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    eventStart: "2026-08-28T00:00:00+09:00",
    eventEnd: "2026-08-28T23:59:59+09:00",
    eventLocation: "김제문화예술회관 대공연장",
    intro: [
      "지역 공연을 고를 때는 티켓 가격만큼 이야기의 난이도와 관람 연령이 가족 구성원에게 맞는지가 중요합니다. 레미제라블 코제트 소녀이야기는 김제문화예술회관 대공연장에서 2026년 8월 28일 열릴 예정으로 등록되어 있습니다.",
      "공개 데이터의 관람료는 전석 5,000원입니다. 저렴한 공연은 좌석이 빠르게 소진될 수 있으므로 실제 판매 상태, 시작 시각과 관람 연령을 공식 예매 화면에서 확인한 뒤 이동 계획을 세우세요.",
    ],
    facts: [
      { label: "장소", value: "김제문화예술회관 대공연장" },
      { label: "공연일", value: "2026년 8월 28일" },
      { label: "분류", value: "뮤지컬·오페라" },
      { label: "관람료", value: "전석 5,000원" },
      { label: "현재 상태", value: "공연예정" },
      { label: "문의", value: "063-540-4176" },
    ],
    takeaway: "김제에서 합리적인 가격의 가족 뮤지컬을 찾는 분에게 좋은 후보입니다. 관람 연령과 좌석 판매 상태를 먼저 확인하세요.",
    sections: [
      {
        heading: "원작을 몰라도 즐길 수 있게 준비하기",
        paragraphs: [
          "아이와 함께라면 작품 전체 줄거리를 설명하기보다 코제트라는 인물이 어떤 선택을 하는지 궁금증을 만들어 주세요. 공연 전에 인물 이름과 시대 배경을 짧게 알고 가면 무대의 노래와 장면을 따라가기 쉬워집니다.",
          "다만 공연의 표현 방식과 권장 연령은 제작사 안내에 따라 달라질 수 있습니다. 어린 관객과 함께라면 어두운 장면이나 큰 음향이 있는지도 문의하는 것이 안전합니다.",
        ],
      },
      {
        heading: "5천원 공연 예매 전 체크리스트",
        paragraphs: ["가격이 낮아도 좌석과 취소 규정은 일반 유료 공연과 같을 수 있습니다."],
        bullets: ["실제 공연 시작·종료 시각", "관람 가능 연령과 보호자 동반 기준", "좌석 지정 방식과 잔여석", "예매 취소 수수료와 티켓 수령 방법"],
      },
      {
        heading: "김제 가족 공연을 찾는 구체적인 검색어",
        paragraphs: [
          "‘김제 5천원 뮤지컬’, ‘김제문화예술회관 가족 공연’, ‘전북 아이와 공연’처럼 지역·비용·동반 대상을 조합하면 검색 결과의 의도가 선명해집니다.",
          "동네고고 지도에서는 공연장 주변의 다른 프로그램과 거리를 함께 비교할 수 있습니다. 같은 날 행사와 겹치지 않는지 살펴보고 여유 있는 이동 시간을 확보하세요.",
        ],
      },
    ],
    tags: ["김제 5천원 뮤지컬", "코제트 소녀이야기", "김제문화예술회관", "전북 가족 공연"],
  },
  {
    slug: "gumi-ice-symphony-concert-guide",
    title: "구미 한여름 밤의 아이스 심포니, 5천원 음악회 관람 가이드",
    seoTitle: "구미 5천원 음악회 아이스 심포니 일정·예매 | 동네고고",
    description: "구미시문화예술회관 한여름 밤의 아이스 심포니 공연일, 5천원 관람료와 음악회 방문 전 체크리스트를 정리했습니다.",
    dek: "한여름 저녁의 음악회를 찾는다면 가격뿐 아니라 공연 시작 시각과 귀가 동선까지 함께 확인해 보세요.",
    category: "문화·전시",
    region: "경북 구미시",
    audience: "음악회 관람객",
    readingMinutes: 4,
    publishedAt: "2026-08-24T06:41:00+09:00",
    modifiedAt: "2026-08-24T06:41:00+09:00",
    sourceCheckedAt: "2026-08-24",
    programId: "program:cultureinfo_events:05853ed01214a77e",
    programName: "[구미] 한여름 밤의 아이스 심포니!",
    programStatus: "공연예정",
    officialUrl: "https://tickets.interpark.com/goods/26009967",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "violet",
    iconPath: "/markers/icon_culture.png",
    imageAlt: "구미 한여름 밤의 아이스 심포니 공식 공연 이미지",
    imageUrl: "https://www.culture.go.kr/upload/rdf/26/07/rdf_2026072721185294634.gif",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    eventStart: "2026-08-26T00:00:00+09:00",
    eventEnd: "2026-08-26T23:59:59+09:00",
    eventLocation: "구미시문화예술회관 대공연장",
    intro: [
      "지역 음악회는 멀리 이동하지 않고도 큰 공연장의 음향과 현장감을 경험할 수 있다는 장점이 있습니다. 한여름 밤의 아이스 심포니는 구미시문화예술회관 대공연장에서 2026년 8월 26일 공연 예정으로 등록되어 있습니다.",
      "공개 정보의 관람료는 전석 5,000원입니다. 정확한 시작 시간, 프로그램 구성과 관람 연령은 예매 화면의 최신 안내를 확인해야 하며, 저녁 공연이라면 종료 뒤 대중교통과 귀가 동선도 함께 살펴보세요.",
    ],
    facts: [
      { label: "장소", value: "구미시문화예술회관 대공연장" },
      { label: "공연일", value: "2026년 8월 26일" },
      { label: "분류", value: "음악·콘서트" },
      { label: "관람료", value: "전석 5,000원" },
      { label: "현재 상태", value: "공연예정" },
      { label: "문의", value: "010-2145-7726" },
    ],
    takeaway: "구미에서 부담 낮은 가격의 음악회를 찾는 분에게 맞습니다. 시작 시간과 프로그램 구성, 귀가 방법을 공식 안내에서 확인하세요.",
    sections: [
      {
        heading: "공연 프로그램을 몰라도 음악회 즐기는 법",
        paragraphs: [
          "곡목을 모두 공부할 필요는 없습니다. 공연 제목에서 기대되는 분위기를 떠올리고 악기 소리나 빠르기의 변화를 따라가면 클래식 음악회가 처음이어도 충분히 즐길 수 있습니다.",
          "아이와 함께라면 공연 중 조용히 있어야 하는 이유와 박수 시점을 미리 설명해 주세요. 관람 연령이 맞는지도 반드시 확인해야 합니다.",
        ],
      },
      {
        heading: "구미문화예술회관 방문 체크리스트",
        paragraphs: ["공연 당일에는 티켓 수령과 입장에 시간이 걸릴 수 있으므로 출발 시간을 넉넉하게 잡으세요."],
        bullets: ["정확한 시작 시각과 러닝타임", "출연진·연주 곡목 변경 공지", "관람 연령과 지연 입장 규정", "티켓 수령 장소와 공연 후 귀가 교통"],
      },
      {
        heading: "구미 여름 음악회를 찾는 검색 조합",
        paragraphs: [
          "‘구미 5천원 음악회’, ‘구미문화예술회관 8월 공연’, ‘경북 여름 콘서트’처럼 비용·장소·계절을 조합하면 원하는 공연을 빠르게 비교할 수 있습니다.",
          "기간이 지난 뒤에도 이 글은 지역 공연 기록으로 남습니다. 다음 시즌 공연을 찾을 때 같은 공연장과 비슷한 가격대의 프로그램을 비교하는 기준으로 활용하세요.",
        ],
      },
    ],
    tags: ["구미 5천원 음악회", "아이스 심포니", "구미문화예술회관", "경북 여름 공연"],
  },
  {
    slug: "seoul-musia-musical-guide",
    title: "서울 대학로 MUSIA 뮤지컬, 종로 공연 예매 전 확인할 것",
    seoTitle: "서울 대학로 MUSIA 뮤지컬 일정·예매 가이드 | 동네고고",
    description: "서경대학교 공연예술센터 MUSIA 나의 첫 사랑은 사슴이었다의 일정, 1만5천원 관람료와 예매 전 확인할 내용을 정리했습니다.",
    dek: "대학로에서 새로운 창작 뮤지컬을 찾는다면 작품명만큼 공연장 위치와 실제 회차, 관람 조건을 함께 비교하세요.",
    category: "문화·전시",
    region: "서울 종로구",
    audience: "뮤지컬 관람객",
    readingMinutes: 4,
    publishedAt: "2026-08-24T06:40:00+09:00",
    modifiedAt: "2026-08-24T06:40:00+09:00",
    sourceCheckedAt: "2026-08-24",
    programId: "program:cultureinfo_events:71667d19f6e5dd52",
    programName: "MUSIA, 나의 첫 사랑은 사슴이었다",
    programStatus: "공연예정",
    officialUrl: "https://tickets.interpark.com/goods/26012027",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "violet",
    iconPath: "/markers/icon_theater.png",
    imageAlt: "MUSIA 나의 첫 사랑은 사슴이었다 공식 공연 이미지",
    imageUrl: "https://www.culture.go.kr/upload/rdf/26/08/rdf_2026081921172102060.gif",
    imageSource: "한국문화정보원 한눈에 보는 문화정보",
    eventStart: "2026-08-30T00:00:00+09:00",
    eventEnd: "2026-08-30T23:59:59+09:00",
    eventLocation: "서경대학교 공연예술센터",
    intro: [
      "대학로 공연을 고를 때는 제목의 분위기만으로 판단하기보다 장르, 공연장과 실제 회차를 먼저 확인해야 합니다. MUSIA, 나의 첫 사랑은 사슴이었다는 서울 종로구 서경대학교 공연예술센터에서 2026년 8월 30일 공연 예정으로 등록되어 있습니다.",
      "공개 데이터의 관람료는 전석 15,000원입니다. 작품의 정확한 러닝타임과 관람 연령, 출연진, 좌석 현황은 공식 예매 페이지에서 최종 확인하세요.",
    ],
    facts: [
      { label: "장소", value: "서경대학교 공연예술센터" },
      { label: "공연일", value: "2026년 8월 30일" },
      { label: "분류", value: "뮤지컬·오페라" },
      { label: "관람료", value: "전석 15,000원" },
      { label: "현재 상태", value: "공연예정" },
      { label: "문의", value: "02-588-7708" },
    ],
    takeaway: "서울 대학로에서 새로운 뮤지컬을 찾는 관객에게 맞는 후보입니다. 작품 정보와 실제 시작 시각, 좌석을 예매 화면에서 확인하세요.",
    sections: [
      {
        heading: "낯선 작품을 고를 때 확인할 기준",
        paragraphs: [
          "익숙하지 않은 제목의 공연은 줄거리를 모두 찾아보기보다 공식 소개에서 장르와 주요 소재, 관람 연령을 먼저 확인하는 것이 좋습니다. 스포일러를 줄이면서도 내 취향과 맞는지 판단할 수 있습니다.",
          "공연 시간이 하루로 표시된 경우 회차 선택의 폭이 좁을 수 있습니다. 좌석이 남아 있더라도 이동과 식사 시간을 포함한 일정이 가능한지 먼저 계산하세요.",
        ],
      },
      {
        heading: "대학로 공연 예매 전 체크리스트",
        paragraphs: ["공연장 이름이 비슷한 경우가 있으므로 주소와 입구까지 확인하면 잘못 이동하는 일을 줄일 수 있습니다."],
        bullets: ["정확한 공연 회차와 러닝타임", "관람 연령·출연진·좌석 정보", "서경대학교 공연예술센터의 정확한 입구", "예매 취소 규정과 지연 입장 가능 여부"],
      },
      {
        heading: "종로 뮤지컬 검색을 구체적으로 만드는 법",
        paragraphs: [
          "‘대학로 8월 뮤지컬’, ‘종로 1만5천원 공연’, ‘서경대학교 공연예술센터 공연’처럼 날짜·비용·장소를 함께 검색하면 예매 가능한 후보를 좁히기 쉽습니다.",
          "공연 전에는 주변 프로그램을 너무 많이 묶기보다 한두 곳만 고르세요. 여유 있는 동선은 예매 시간에 늦을 위험을 줄이고 공연에 집중할 시간을 확보해 줍니다.",
        ],
      },
    ],
    tags: ["대학로 8월 뮤지컬", "MUSIA 뮤지컬", "종로 1만5천원 공연", "서경대학교 공연예술센터"],
  },
  {
    slug: "seoul-guro-free-parent-growth-class",
    title: "서울 구로 무료 부모교육, ‘부모 역할 리모델링’ 신청 전 확인할 것",
    seoTitle: "서울 구로 무료 부모교육 신청 가이드 | 부모 역할 리모델링 | 동네고고",
    description: "구로구 우리동네키움센터의 무료 부모교육 ‘부모 역할 리모델링’ 대상, 접수 기간, 일정과 신청 전 확인할 내용을 정리했습니다.",
    dek: "아이를 바꾸는 기술보다 지금 가족에게 필요한 부모 역할을 다시 살펴보고 싶은 분을 위한 단회 부모교육을 확인해 보세요.",
    category: "교육",
    region: "서울 구로구",
    audience: "성인·보호자",
    readingMinutes: 4,
    publishedAt: "2026-08-23T06:58:00+09:00",
    modifiedAt: "2026-08-23T06:58:00+09:00",
    sourceCheckedAt: "2026-08-23",
    programId: "program:reservations:e75e1975f90b4eb9",
    programName: "함께 성장 클래스: 부모 역할 리모델링",
    programStatus: "안내중",
    officialUrl: "https://umppa.seoul.go.kr/icare/user/chilProgrm/orgideaExprnCtzn/BD_selectOrgideaExprnCtzn.do?q_progrmCl=1000&q_placeCode=400&q_progrmSn=3305",
    sourceName: "서울시 공공서비스예약(종합) 정보",
    accent: "lime",
    iconPath: "/markers/icon_digital.png",
    imageAlt: "함께 성장 클래스 부모 역할 리모델링 공식 프로그램 포스터",
    imageUrl: "https://umppa.seoul.go.kr/icare/webcontent/icare/upload/orgideaExprnCtznFile/2026/8/21/d15140a0-3094-4326-b63b-0fcd1e279963.jpg",
    imageSource: "서울시 문화행사 공공서비스예약 정보",
    eventStart: "2026-09-14T00:00:00+09:00",
    eventEnd: "2026-09-14T00:00:00+09:00",
    eventLocation: "거점 4호 우리동네키움센터 4층 미디어실",
    intro: [
      "부모교육을 찾을 때는 ‘좋은 부모가 되는 정답’을 알려 주는지보다, 지금 우리 가족의 역할과 관계를 돌아볼 질문을 얻을 수 있는지 살펴보는 편이 좋습니다. 구로구 거점 4호 우리동네키움센터에서 열리는 이번 함께 성장 클래스는 부모 역할을 다시 설계한다는 주제로 진행되는 성인 대상 프로그램입니다.",
      "동네고고가 2026년 8월 23일 확인한 공개 정보에 따르면 참가비는 무료이며 정원은 15명, 대기자는 5명입니다. 접수는 8월 25일부터 9월 11일까지로 안내되어 있습니다. 단회 교육이므로 신청 전에 정확한 시작 시간과 참여 방식, 보호자만 참석하는 수업인지 여부를 공식 화면에서 다시 확인하세요.",
    ],
    facts: [
      { label: "장소", value: "거점 4호 우리동네키움센터 4층 미디어실" },
      { label: "프로그램 일정", value: "2026년 9월 14일" },
      { label: "접수 기간", value: "2026년 8월 25일~9월 11일" },
      { label: "대상", value: "성인·보호자" },
      { label: "정원", value: "15명 · 대기 5명" },
      { label: "비용", value: "무료" },
    ],
    takeaway: "무료 단회 부모교육을 찾는 구로구 보호자에게 알맞은 후보입니다. 접수 시작일과 정확한 수업 시간을 공식 안내에서 마지막으로 확인하세요.",
    sections: [
      {
        heading: "부모 역할을 ‘리모델링’한다는 뜻",
        paragraphs: [
          "가족의 생활 리듬과 아이의 발달 단계가 달라지면 예전에 잘 맞았던 대화 방식이 더는 통하지 않을 수 있습니다. 이때 필요한 것은 부모 역할을 전부 바꾸는 일이 아니라, 지금 반복되는 갈등에서 어떤 기대와 규칙을 조정할지 구체적으로 살펴보는 과정입니다.",
          "교육을 들으며 최근 힘들었던 상황 하나를 떠올리고, 그때 부모가 기대한 것과 아이가 이해한 것을 따로 적어 보세요. 막연한 자책보다 실제 장면을 중심으로 질문하면 수업 내용을 집에서도 적용하기 쉬워집니다.",
        ],
      },
      {
        heading: "신청 전에 확인할 네 가지",
        paragraphs: [
          "공개 데이터에는 날짜와 접수 기간이 표시되어 있지만 세부 운영 조건은 바뀔 수 있습니다. 특히 단회 강좌는 시간을 놓치면 대체 회차를 찾기 어려우므로 아래 항목을 먼저 확인하는 것이 안전합니다.",
        ],
        bullets: [
          "정확한 시작·종료 시간과 전체 소요시간",
          "보호자만 참석하는지, 자녀 동반이 가능한지",
          "구로구 거주자 또는 센터 이용자 우선 조건이 있는지",
          "취소 시 대기자에게 자리가 넘어가는 시점과 연락 방식",
        ],
      },
      {
        heading: "이런 검색 의도라면 잘 맞아요",
        paragraphs: [
          "‘구로구 무료 부모교육’, ‘우리동네키움센터 보호자 강좌’, ‘서울 초등 부모 역할 교육’처럼 지역·비용·대상을 함께 찾는 분에게 적합합니다. 자녀 연령별 훈육법이나 장기 상담이 필요한 경우에는 이번 단회 수업만으로 해결하려 하기보다 후속 상담 또는 연속 과정이 있는지도 함께 문의하세요.",
          "참여 뒤에는 배운 내용을 모두 실천하려고 하기보다 가족이 일주일 동안 시험해 볼 대화 습관 하나만 정해 보세요. 변화의 기준을 작게 잡으면 수업이 좋은 정보로 끝나지 않고 실제 생활의 변화로 이어질 가능성이 높아집니다.",
        ],
      },
    ],
    tags: ["구로구 무료 부모교육", "우리동네키움센터", "서울 보호자 강좌", "부모 역할 교육"],
  },
  {
    slug: "bupyeong-free-kids-ai-coding-class",
    title: "인천 부평 무료 어린이 AI 코딩 강좌, 레고로 시작하는 첫 코딩",
    seoTitle: "인천 부평 무료 어린이 AI 코딩 강좌 신청 가이드 | 동네고고",
    description: "부평도서관에서 열리는 무료 어린이 AI 코딩 강좌의 대상, 일정, 신청 마감일과 보호자가 확인할 준비 사항을 한눈에 정리했습니다.",
    dek: "화면 속 문법부터 외우는 수업보다, 손으로 조립한 결과물이 움직이는 경험이 먼저 필요한 아이에게 어울리는 무료 강좌를 살펴봅니다.",
    category: "교육",
    region: "인천 부평구",
    audience: "아동·보호자",
    readingMinutes: 4,
    publishedAt: "2026-08-22T09:10:00+09:00",
    modifiedAt: "2026-08-22T09:10:00+09:00",
    sourceCheckedAt: "2026-08-22",
    programId: "program:lifelong_standard:b3e1e044badc7e8e",
    programName: "레고 스파티크프라임과 알티노라이트로 배우는 AI 코딩",
    programStatus: "접수중",
    officialUrl: "https://lib.ice.go.kr/bupyeong",
    sourceName: "전국평생학습강좌표준데이터",
    accent: "lime",
    iconPath: "/markers/icon_digital.png",
    imageAlt: "어린이 디지털 교육을 상징하는 동네고고 아이콘",
    intro: [
      "아이의 첫 코딩 수업을 찾을 때 가장 먼저 볼 것은 ‘어떤 언어를 배우나’보다 ‘직접 만들어 보는 시간이 충분한가’입니다. 인천광역시교육청 부평도서관에서 열리는 이 강좌는 레고 스파이크 프라임과 알티노라이트를 활용해 작품을 만들고 코딩으로 완성하는 오프라인 수업입니다.",
      "동네고고에 등록된 공개 정보를 기준으로 수강료는 무료, 대상은 아동, 정원은 10명입니다. 소규모 수업을 찾는 보호자에게 특히 눈에 띄지만, 연령 범위와 준비물은 신청 전에 운영기관 공지를 한 번 더 확인하는 편이 안전합니다.",
    ],
    facts: [
      { label: "장소", value: "인천광역시교육청 부평도서관 나래울실" },
      { label: "수업 기간", value: "2026년 9월 3일~10월 29일" },
      { label: "수업 시간", value: "매주 목요일 16:00~18:00" },
      { label: "신청 마감", value: "2026년 8월 28일 23:59 예정" },
      { label: "대상·정원", value: "아동 · 10명" },
      { label: "비용", value: "무료" },
    ],
    takeaway: "무료·소규모·오프라인이라는 세 조건이 장점입니다. 아이가 목요일 오후에 꾸준히 참여할 수 있는지부터 확인하세요.",
    sections: [
      {
        heading: "이 강좌가 첫 코딩에 잘 맞는 이유",
        paragraphs: [
          "처음 코딩을 접하는 아이는 화면의 정답보다 자신이 만든 구조물이 실제로 반응하는 순간에 더 쉽게 몰입합니다. 레고 조립과 코딩을 연결하면 ‘명령을 바꾸면 결과도 달라진다’는 원리를 눈으로 확인할 수 있습니다. 결과물이 바로 보이기 때문에 틀리는 과정도 실패라기보다 다음 시도를 위한 단서가 됩니다.",
          "다만 교구를 쓴다는 이유만으로 모든 아이에게 쉬운 것은 아닙니다. 두 시간 수업에 집중할 수 있는지, 조립 활동을 좋아하는지, 여러 주 동안 같은 요일에 참여할 수 있는지를 함께 살펴보면 중도 이탈 가능성을 줄일 수 있습니다.",
        ],
      },
      {
        heading: "보호자가 신청 전에 확인할 네 가지",
        paragraphs: [
          "공개 데이터에는 핵심 일정과 대상이 담겨 있지만, 실제 접수 화면에는 학년 기준이나 결석 규정처럼 더 구체적인 조건이 추가될 수 있습니다. 신청 버튼을 누르기 전에 아래 항목을 확인해 두세요.",
        ],
        bullets: [
          "정확한 참여 학년과 보호자 동반 여부",
          "레고 교구 제공 여부와 개인 준비물",
          "총 수업 횟수, 휴강일, 결석 시 보강 가능 여부",
          "도서관 회원가입이나 별도 본인인증 필요 여부",
        ],
      },
      {
        heading: "이런 아이에게 추천해요",
        paragraphs: [
          "블록 조립을 좋아하지만 코딩 학원은 아직 부담스러운 아이, 화면 수업보다 손으로 만드는 활동에 오래 집중하는 아이, 완성품보다 시행착오 자체를 즐기는 아이에게 좋은 출발점이 될 수 있습니다. 반대로 정해진 순서대로 조립하는 활동을 답답해하거나 목요일 오후 일정이 자주 바뀌는 가정이라면 단기 체험형 수업부터 시작하는 편이 낫습니다.",
          "검색할 때는 ‘부평 어린이 코딩’만 입력하기보다 ‘인천 무료 어린이 코딩’, ‘부평도서관 초등 AI 강좌’처럼 지역·비용·대상을 함께 넣으면 비슷한 프로그램을 더 빠르게 비교할 수 있습니다. 동네고고 지도에서도 교육 아이콘과 무료 조건을 함께 보면 이동 가능한 후보를 좁히기 쉽습니다.",
        ],
      },
    ],
    tags: ["인천 어린이 코딩", "부평도서관 강좌", "무료 AI 교육", "초등 코딩"],
  },
  {
    slug: "cheongju-picture-book-garden-exhibition-guide",
    title: "청주 무료 그림책 전시, 《빛나는 아이들, 이수지의 그림책》 관람 가이드",
    seoTitle: "청주 무료 그림책 전시 관람 가이드 | 그림책정원1937 | 동네고고",
    description: "청주 그림책정원1937에서 진행 중인 무료 기획전시의 기간, 위치와 아이와 함께 보기 전 알아둘 관람 포인트를 정리했습니다.",
    dek: "아이와 무엇을 봐야 할지 미리 정답을 만들기보다, 한 장면 앞에서 서로 다른 이야기를 발견하는 시간을 준비해 보세요.",
    category: "문화·전시",
    region: "충북 청주시",
    audience: "가족·그림책 독자",
    readingMinutes: 5,
    publishedAt: "2026-08-22T10:20:00+09:00",
    modifiedAt: "2026-08-22T10:20:00+09:00",
    sourceCheckedAt: "2026-08-22",
    programId: "program:cultureinfo_events:8757defd82494239",
    programName: "그림책정원1937 2026년 1차 기획전시 《빛나는 아이들, 이수지의 그림책》",
    programStatus: "진행중",
    officialUrl: "https://www.cbfc.or.kr/home/sub.php?menukey=6444&mod=view&no=2335867",
    sourceName: "한국문화정보원 한눈에 보는 문화정보",
    accent: "violet",
    iconPath: "/markers/icon_exhibition.png",
    imageAlt: "문화 전시를 상징하는 동네고고 아이콘",
    intro: [
      "그림책 전시는 ‘아이를 위한 전시’로만 생각하기 쉽지만, 같은 장면을 어른과 아이가 전혀 다르게 읽는다는 점에서 가족 대화의 좋은 출발점이 됩니다. 청주 그림책정원1937에서는 2026년 첫 기획전시로 《빛나는 아이들, 이수지의 그림책》을 진행하고 있습니다.",
      "동네고고가 확인한 공개 정보상 전시는 8월 4일부터 11월 8일까지이며 관람료는 무료입니다. 전시의 세부 구성과 휴관일, 입장 가능 시간은 방문일에 따라 달라질 수 있으므로 출발 전 공식 안내를 확인하세요.",
    ],
    facts: [
      { label: "장소", value: "그림책정원1937" },
      { label: "주소", value: "충북 청주시 상당구 상당로 82" },
      { label: "전시 기간", value: "2026년 8월 4일~11월 8일" },
      { label: "상태", value: "진행중" },
      { label: "관람료", value: "무료" },
      { label: "문의", value: "043-299-9366" },
    ],
    takeaway: "무료로 여유 있게 볼 수 있는 장기 전시입니다. 휴관일과 당일 운영시간만 확인하면 가족 나들이 일정에 넣기 좋습니다.",
    sections: [
      {
        heading: "그림책 전시는 어떻게 보면 좋을까요?",
        paragraphs: [
          "책을 읽을 때는 페이지 순서가 관람의 리듬을 정하지만, 전시장에서는 관람자가 순서와 거리를 선택합니다. 아이가 한 장면 앞에 오래 머물면 다음 작품으로 재촉하기보다 ‘무엇이 먼저 보였어?’라고 물어보세요. 작품의 의미를 맞히는 질문보다 관찰한 것을 말하게 하는 질문이 더 오래 기억에 남습니다.",
          "전시 제목에 담긴 ‘빛나는 아이들’이라는 표현도 좋은 대화 소재입니다. 전시장에 들어가기 전 아이에게 빛난다는 말이 어떤 색과 표정으로 떠오르는지 묻고, 관람 뒤 답이 달라졌는지 비교해 보세요. 작품의 세부 내용을 미리 단정하지 않으면서도 관람 경험을 풍성하게 만드는 방법입니다.",
        ],
      },
      {
        heading: "아이와 갈 때 챙기면 좋은 것",
        paragraphs: [
          "무료 전시는 예약 없이 갈 수 있는 경우가 많지만, 단체 관람이나 특별 프로그램이 있는 날에는 동선이 달라질 수 있습니다. 유아와 함께라면 관람 시간도 길게 잡기보다 짧은 집중 시간을 여러 번 나누는 편이 편안합니다.",
        ],
        bullets: [
          "방문 당일 운영시간과 휴관 여부",
          "주차장 또는 대중교통 하차 지점",
          "유모차 이동 가능 구간과 물품 보관 공간",
          "연계 체험·도슨트 프로그램의 별도 예약 여부",
        ],
      },
      {
        heading: "전시 뒤에도 경험을 이어가는 방법",
        paragraphs: [
          "관람을 마친 뒤에는 가장 마음에 든 장면을 서로 한 문장으로 말해 보세요. 아이가 고른 장면을 어른이 다시 설명하고, 어른이 고른 장면을 아이가 설명하게 하면 같은 전시가 두 개의 이야기로 남습니다. 집에 돌아와 ‘오늘 본 전시의 다음 페이지’를 한 장 그려 보는 것도 부담 없는 후속 활동입니다.",
          "청주에서 다른 가족 문화행사까지 함께 찾고 싶다면 ‘청주 무료 전시’, ‘청주 아이와 갈 만한 곳’, ‘상당구 문화행사’처럼 지역과 방문 목적을 조합해 보세요. 동네고고에서는 전시·미술 아이콘을 중심으로 주변 프로그램과 거리를 함께 비교할 수 있습니다.",
        ],
      },
    ],
    tags: ["청주 무료 전시", "그림책정원1937", "아이와 청주", "이수지 그림책"],
  },
  {
    slug: "seoul-junggu-chungmu-swimming-pool-checklist",
    title: "서울 중구 수영장 찾기, 충무스포츠센터 접수 전 확인할 6가지",
    seoTitle: "서울 중구 충무스포츠센터 수영장 접수 가이드 | 동네고고",
    description: "충무스포츠센터 수영장 이용을 알아보는 분을 위해 접수 기간, 위치, 비용 확인법과 강습 선택 체크리스트를 정리했습니다.",
    dek: "가까운 수영장을 발견한 다음에는 시간표, 비용, 강습 단계와 이동 시간을 함께 비교해야 실제로 꾸준히 다닐 수 있습니다.",
    category: "체육",
    region: "서울 중구",
    audience: "생활체육 입문자",
    readingMinutes: 4,
    publishedAt: "2026-08-22T11:30:00+09:00",
    modifiedAt: "2026-08-22T11:30:00+09:00",
    sourceCheckedAt: "2026-08-22",
    programId: "program:reservations:57d9eeabbbe79473",
    programName: "[서울 중구] 충무스포츠센터 수영장",
    programStatus: "접수중",
    officialUrl: "https://www.e-junggu.or.kr/fmcs/314?action=list&facilities_type=C&base_date=20260701&center=JUNGGU01&type=&part=02&place=6",
    sourceName: "서울시 공공서비스예약(종합) 정보",
    accent: "blue",
    iconPath: "/markers/icon_swimming.png",
    imageAlt: "수영 생활체육을 상징하는 동네고고 아이콘",
    intro: [
      "수영장은 집이나 직장에서 가깝다는 이유만으로 고르기 어렵습니다. 원하는 시간대에 자리가 있는지, 자유수영인지 강습인지, 내 수준에 맞는 반이 있는지를 함께 봐야 등록 뒤에도 꾸준히 다닐 수 있습니다.",
      "동네고고 공개 데이터에서 충무스포츠센터 수영장은 현재 접수중으로 확인되며, 이용 기간은 2026년 8월 31일까지로 표시되어 있습니다. 비용은 유료이지만 강습별 금액과 잔여 인원은 공식 예약 화면에서 최종 확인해야 합니다.",
    ],
    facts: [
      { label: "시설", value: "충무스포츠센터 수영장" },
      { label: "지역", value: "서울 중구" },
      { label: "이용 기간", value: "2026년 7월 21일~8월 31일" },
      { label: "접수 마감", value: "2026년 8월 31일 00:00 예정" },
      { label: "대상", value: "제한없음으로 등록" },
      { label: "비용", value: "유료 · 반별 금액 확인 필요" },
    ],
    takeaway: "접수중 표시는 출발점입니다. 원하는 반의 잔여석·정확한 시간·월 이용료를 공식 페이지에서 확인한 뒤 결제하세요.",
    sections: [
      {
        heading: "등록 전에 꼭 비교할 여섯 가지",
        paragraphs: [
          "생활체육은 프로그램의 유명세보다 생활 동선과의 궁합이 중요합니다. 지도상 거리가 짧아도 환승이나 퇴근 시간 혼잡 때문에 체감 이동 시간이 길 수 있습니다. 아래 항목을 한 화면에 적어 두면 비슷한 시설을 비교하기 쉬워집니다.",
        ],
        bullets: [
          "자유수영·강습 구분과 초급·중급 등 난이도",
          "입수 시간뿐 아니라 탈의·샤워 시간을 포함한 전체 소요시간",
          "월 이용료, 등록 수수료, 할인 대상과 증빙서류",
          "신규 회원 접수일과 기존 회원 재등록 기간",
          "준비물, 수영모 규정, 개인 사물함 이용 조건",
          "집·직장에서 실제 출발 시간 기준 대중교통과 도보 거리",
        ],
      },
      {
        heading: "‘대상 제한없음’이 모든 반에 적용되지는 않아요",
        paragraphs: [
          "공공 데이터의 대상 항목은 시설 전체를 넓게 설명하는 경우가 있습니다. 실제 강습은 연령, 수영 수준, 성별 또는 이용 시간에 따라 반이 나뉠 수 있습니다. ‘제한없음’만 보고 바로 결제하지 말고 선택한 반의 상세 조건을 확인하세요.",
          "처음 배우는 경우에는 수업 이름보다 진도 기준을 물어보는 것이 정확합니다. 물 적응부터 시작하는지, 자유형 호흡을 어느 정도 할 수 있어야 하는지, 첫날 레벨 확인이 있는지를 문의하면 자신에게 맞지 않는 반을 고를 가능성이 줄어듭니다.",
        ],
      },
      {
        heading: "가까운 수영장을 더 잘 찾는 검색법",
        paragraphs: [
          "‘서울 수영장’처럼 넓게 검색하면 결과가 너무 많습니다. ‘중구 저녁 수영 강습’, ‘충무스포츠센터 자유수영’, ‘퇴근 후 수영장’처럼 지역·시간·이용 방식을 함께 입력하세요. 후보가 두세 곳으로 줄면 거리순보다 실제 출발 시간 기준의 이동 시간을 비교하는 것이 좋습니다.",
          "동네고고 지도에서는 수영 아이콘을 선택한 뒤 현재 위치와 시설 간 거리를 확인할 수 있습니다. 접수 상태가 바뀌거나 정원이 먼저 찰 수 있으므로, 마음에 드는 프로그램은 공식 페이지에서 즉시 잔여석을 확인하는 습관이 가장 확실합니다.",
        ],
      },
    ],
    tags: ["서울 중구 수영장", "충무스포츠센터", "생활체육", "수영 강습"],
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((post) => post.slug === slug);
}

export function koreanDate(value: string): string {
  return new Intl.DateTimeFormat("ko-KR", {
    timeZone: "Asia/Seoul",
    year: "numeric",
    month: "long",
    day: "numeric",
  }).format(new Date(value));
}

export function blogPostUrl(post: BlogPost): string {
  return `https://www.dongnegogo.com/blog/${post.slug}`;
}
